import SigGolfCandidate.T3.Nonbinary.EncodingCounts
import SigGolfCandidate.T3.Gate6.SourceBridge
import SigGolfCandidate.T3.Gate6.SourceBudget
import SigGolfCandidate.T3.Gate6.Closing115Numeric

#print axioms SigGolfResearch.Gate6.Source.actual_acceptance_exact
#print axioms SigGolfResearch.Gate6.Source.actual_mark_joint_exact
#print axioms SigGolfCandidate.T3.EncodingCounting.decoder_acceptance_count
#print axioms SigGolfCandidate.T3.EncodingCounting.encoding_uniform_probability
#print axioms SigGolfCandidate.T3.BaseAudit.source_signing_envelope
#print axioms SigGolfResearch.Gate3Closing115.mean_bound
#print axioms SigGolfResearch.Gate3Closing115.variance_excess
#print axioms SigGolfResearch.Gate3Closing115.reuse_bound
#print axioms SigGolfResearch.Gate3Closing115.prefix_rate
#print axioms SigGolfResearch.Gate3Closing115.encoding_rate
#print axioms SigGolfResearch.Gate3Closing115.small_excess_rate
#print axioms SigGolfResearch.Gate3Closing115.near_rate
#print axioms SigGolfResearch.Gate3Closing115.small_first_rate
#print axioms SigGolfResearch.Gate3Closing115.pointwise_excess
#print axioms SigGolfResearch.Gate3Closing115.small_closing_real
#print axioms SigGolfResearch.Gate3Closing115.large_closing_real
