import SigGolfCandidate.T3.Gate6.DigestCounting
import SigGolfCandidate.T3.Gate6.NearCoverage
#print axioms SigGolfCandidate.T3.BPORS.History.atIndex_cons
#print axioms SigGolfCandidate.T3.BPORS.History.finiteAverage_constant
#print axioms SigGolfCandidate.T3.BPORS.History.average_binomial_commute
#print axioms SigGolfCandidate.T3.BPORS.History.finiteAverage_choice
#print axioms SigGolfCandidate.T3.BPORS.History.uniform_marked_word_atIndex
#print axioms SigGolfCandidate.T3.BPORS.History.word_forest_moment
#print axioms SigGolfCandidate.T3.BPORS.History.uniform_proposal_forest_moment
#print axioms SigGolfCandidate.T3.BPORS.History.uniform_proposal_mean_bound
#print axioms SigGolfCandidate.T3.BPORS.History.uniform_proposal_excess_bound
#print axioms SigGolfCandidate.T3.BPORS.History.word_near_forest_moment
#print axioms SigGolfCandidate.T3.BPORS.History.uniform_proposal_near_bound
#print axioms SigGolfCandidate.T3.BPORS.History.exposedLeaves_card_le
#print axioms SigGolfCandidate.T3.BPORS.History.wordTable_column
#print axioms SigGolfCandidate.T3.BPORS.History.wordTable_envelope
#print axioms SigGolfCandidate.T3.BPORS.History.history_covered_probability_le
#print axioms SigGolfCandidate.T3.BPORS.History.finiteAverage_commute
#print axioms SigGolfCandidate.T3.BPORS.History.average_joint_commute
#print axioms SigGolfCandidate.T3.BPORS.History.uniform_word_joint_count
#print axioms SigGolfCandidate.T3.BPORS.History.uniform_marked_word_joint
#print axioms SigGolfCandidate.T3.BPORS.History.uniform_envelope_negative_correlation
#print axioms SigGolfCandidate.T3.BPORS.History.uniformWordAverage_mul_right
#print axioms SigGolfCandidate.T3.BPORS.History.marked_marginal_envelope
#print axioms SigGolfCandidate.T3.BPORS.History.marked_envelope_negative_correlation
#print axioms SigGolfCandidate.T3.BPORS.History.word_first_moment
#print axioms SigGolfCandidate.T3.BPORS.History.forest_negative_correlation
#print axioms SigGolfCandidate.T3.BPORS.History.fullPrice_ne_top
#print axioms SigGolfCandidate.T3.BPORS.History.fullPrice_mean
#print axioms SigGolfCandidate.T3.BPORS.History.fullPrice_mean_bound
#print axioms SigGolfCandidate.T3.BPORS.History.fullPrice_secondMoment_bound
#print axioms SigGolfCandidate.T3.BPORS.History.unit_excess_le_square
#print axioms SigGolfCandidate.T3.BPORS.History.uniformWordAverage_constant
#print axioms SigGolfCandidate.T3.BPORS.History.fullPrice_excess_bound
#print axioms SigGolfCandidate.T3.BPORS.History.near_mean_at_index
#print axioms SigGolfCandidate.T3.BPORS.History.fullNearPrice_bound
#print axioms SigGolfCandidate.T3.DigestCounting.packed_card
#print axioms SigGolfCandidate.T3.DigestCounting.acceptanceProbability_eq_p0
#print axioms SigGolfCandidate.T3.DigestCounting.digest_probability_eq_p0
#print axioms SigGolfCandidate.T3.Acceptance.acceptanceProbability_le_one_sixteenth
#print axioms SigGolfResearch.Gate6.gated_event_probability
#print axioms SigGolfResearch.Gate6.digest_gated_event_probability
#print axioms SigGolfResearch.Gate6.raw_at_draw_event
#print axioms SigGolfResearch.Gate6.digest_at_gated_event_probability
#print axioms SigGolfCandidate.T3.BPORS.omitCovered_of_all_but
#print axioms SigGolfCandidate.T3.BPORS.omitCovered_count
#print axioms SigGolfCandidate.T3.BPORS.bucket_omitCovered_count
#print axioms SigGolfCandidate.T3.BPORS.bucket_omitCovered_probability
#print axioms SigGolfCandidate.T3.BPORS.uniform_forall_probability
#print axioms SigGolfCandidate.T3.BPORS.nearCovered_of_all_but
#print axioms SigGolfCandidate.T3.BPORS.nearCovered_probability
#print axioms SigGolfCandidate.T3.BPORS.near_denominator_product
#print axioms SigGolfCandidate.T3.BPORS.div_bucket_leaf_power
#print axioms SigGolfCandidate.T3.BPORS.nearCovered_le_rawWordEnvelope
#print axioms SigGolfCandidate.T3.BPORS.nearCovered_le_wordEnvelope
