import SigGolfCandidate.T3.Gate6.Budget
import SigGolfCandidate.T3.Gate6.Coverage
import SigGolfCandidate.T3.Gate6.DigestSampling
#print axioms SigGolfResearch.Gate6.markedLabel_card
#print axioms SigGolfResearch.Gate6.rawRecord_card
#print axioms SigGolfResearch.Gate6.payload_card
#print axioms SigGolfResearch.Gate6.witness_injective
#print axioms SigGolfResearch.Gate6.witness_auth
#print axioms SigGolfResearch.Gate6.accepted_witness
#print axioms SigGolfResearch.Gate6.accepted_card
#print axioms SigGolfResearch.Gate6.fibre_card
#print axioms SigGolfResearch.Gate6.payload_accepted_card
#print axioms SigGolfResearch.Gate6.fresh_acceptance
#print axioms SigGolfResearch.Gate6.fresh_mark_joint
#print axioms SigGolfResearch.Gate6.fresh_mark_conditional
#print axioms SigGolfResearch.Gate6.childSet_card
#print axioms SigGolfResearch.Gate6.family_card
#print axioms SigGolfResearch.Gate6.child_weight_sum
#print axioms SigGolfResearch.Gate6.family_weight_sum
#print axioms SigGolfResearch.Gate6.mod_pow_sum_generic
#print axioms SigGolfResearch.Gate6.sum_pow_mod_pred_generic
#print axioms SigGolfResearch.Gate6.generic_capped_card
#print axioms SigGolfResearch.Gate6.packedSetCount_value
#print axioms SigGolfResearch.Gate6.family_card_packed_generic
#print axioms SigGolfResearch.Gate6.coefficient_power_mod
#print axioms SigGolfResearch.Gate6.family_card_packed
#print axioms SigGolfResearch.Gate6.dp_coefficient_packed
#print axioms SigGolfResearch.Gate6.capped_family_card
#print axioms SigGolfResearch.Gate6.enumeration_card
#print axioms SigGolfResearch.Gate6.sigma_card_constant
#print axioms SigGolfResearch.Gate6.enumeration_family_card
#print axioms SigGolfResearch.Gate6.ordered_accepted_card
#print axioms SigGolfResearch.Gate6.digestRecord_injective
#print axioms SigGolfResearch.Gate6.digestRecord_bijective
#print axioms SigGolfResearch.Gate6.digest_event
#print axioms SigGolfResearch.Gate6.digest_mark_conditional
#print axioms SigGolfResearch.Gate6.fresh_acceptance_exact
#print axioms SigGolfResearch.Gate6.fresh_mark_joint_exact
#print axioms SigGolfResearch.Gate6.digest_acceptance_exact
#print axioms SigGolfResearch.Gate6.digest_mark_joint_exact
#print axioms SigGolfResearch.Gate6.digestRecord_index
#print axioms SigGolfResearch.Gate6.digestRecord_bucket
#print axioms SigGolfResearch.Gate6.digestRecord_leaf
#print axioms SigGolfResearch.Gate6.digestRecord_gate
#print axioms SigGolfResearch.Gate6.digestRecord_gate_accept
#print axioms SigGolfResearch.Gate6.digest_acceptance_iff
#print axioms SigGolfResearch.Gate6.Budget.digest_geometric_step
#print axioms SigGolfResearch.Gate6.Budget.probability_floor
#print axioms SigGolfResearch.Gate6.Budget.probability_matches
#print axioms SigGolfResearch.Gate6.Budget.signing_envelope
#print axioms SigGolfResearch.Gate6.Budget.physical_bank_work
#print axioms SigGolfResearch.Gate6.Budget.fixed_signing_work
#print axioms SigGolfResearch.Gate6.Budget.signature_layout_bytes
#print axioms SigGolfResearch.Gate6.Moments.covered_count
#print axioms SigGolfResearch.Gate6.Moments.covered_probability
#print axioms SigGolfResearch.Gate6.Moments.covered_probability_le
#print axioms SigGolfResearch.Gate6.Moments.covered_product_count
#print axioms SigGolfResearch.Gate6.Moments.three_openings_polynomial
#print axioms SigGolfResearch.Gate6.Moments.two_openings_polynomial
#print axioms SigGolfResearch.Gate6.Moments.bucket_thinning
#print axioms SigGolfResearch.Gate6.Moments.near_bucket_thinning
#print axioms SigGolfResearch.Gate6.Moments.bucket_covered_count
#print axioms SigGolfResearch.Gate6.Moments.bucket_covered_probability
#print axioms SigGolfResearch.Gate6.Moments.bucket_product_count
#print axioms SigGolfResearch.Gate6.Moments.bpors_covered_probability
#print axioms SigGolfResearch.Gate6.Moments.distinct_bucket_cross_moment
#print axioms SigGolfResearch.Gate6.Moments.envelope_cast
#print axioms SigGolfResearch.Gate6.Moments.factorialPolynomial_eval
#print axioms SigGolfResearch.Gate6.Moments.full_envelope
#print axioms SigGolfResearch.Gate6.Moments.square_polynomial
#print axioms SigGolfResearch.Gate6.Moments.full_square_envelope
#print axioms SigGolfResearch.Gate6.Moments.envelope_thinning
#print axioms SigGolfResearch.Gate6.Moments.same_bucket_second_moment
#print axioms SigGolfResearch.Gate6.Moments.different_bucket_second_moment
#print axioms SigGolfResearch.Gate6.Moments.bucket_pair_moment
#print axioms SigGolfResearch.Gate6.Moments.coordinate_second_moment
#print axioms SigGolfResearch.Gate6.Moments.expected_uniform_eq_finiteAverage
#print axioms SigGolfResearch.Gate6.Moments.finiteAverage_product
#print axioms SigGolfResearch.Gate6.Moments.uniform_coordinate_product
#print axioms SigGolfResearch.Gate6.Moments.finiteAverage_equiv
#print axioms SigGolfResearch.Gate6.Moments.finiteAverage_pair
#print axioms SigGolfResearch.Gate6.Moments.uniformWordAverage_succ
#print axioms SigGolfResearch.Gate6.Moments.word_array_average
#print axioms SigGolfResearch.Gate6.Moments.seven_coordinate_second_moment
#print axioms SigGolfResearch.Gate6.Moments.bucket_first_moment
#print axioms SigGolfResearch.Gate6.Moments.coordinate_first_moment
#print axioms SigGolfResearch.Gate6.Moments.seven_coordinate_first_moment
#print axioms SigGolfResearch.Gate6.Moments.Numeric.mean_polynomial
#print axioms SigGolfResearch.Gate6.Moments.Numeric.variance_polynomial
#print axioms SigGolfResearch.Gate6.Moments.Numeric.near_polynomial
#print axioms SigGolfResearch.Gate6.Moments.Numeric.envelope_power
#print axioms SigGolfResearch.Gate6.Moments.Numeric.mean_envelope_power
#print axioms SigGolfResearch.Gate6.Moments.Numeric.variance_envelope_power
#print axioms SigGolfResearch.Gate6.Moments.Numeric.firstMoment_coefficients
#print axioms SigGolfResearch.Gate6.Moments.Numeric.secondMoment_coefficients
#print axioms SigGolfResearch.Gate6.Moments.Numeric.firstMoment_power_coefficients
#print axioms SigGolfResearch.Gate6.Moments.Numeric.secondMoment_power_coefficients
#print axioms SigGolfResearch.Gate6.Moments.Numeric.binomial_envelope_le_poisson
#print axioms SigGolfResearch.Gate6.Moments.Numeric.forest_first_moment
#print axioms SigGolfResearch.Gate6.Moments.Numeric.forest_second_moment
#print axioms SigGolfResearch.Gate6.Moments.Numeric.forest_binomial_first_bound
#print axioms SigGolfResearch.Gate6.Moments.Numeric.forest_binomial_second_bound
#print axioms SigGolfResearch.Gate6.Moments.Numeric.poisson_mean_bound
#print axioms SigGolfResearch.Gate6.Moments.Numeric.poisson_excess_bound
#print axioms SigGolfResearch.Gate6.Moments.Numeric.poisson_near_bound
#print axioms SigGolfResearch.Gate6.Moments.Numeric.poisson_near_tight_bound
#print axioms SigGolfResearch.Gate6.Moments.Numeric.near_coordinate_first_moment
#print axioms SigGolfResearch.Gate6.Moments.Numeric.near_envelope_product
#print axioms SigGolfResearch.Gate6.Moments.Numeric.near_forest_first_moment
#print axioms SigGolfResearch.Gate6.Moments.Numeric.near_forest_binomial_bound
#print axioms SigGolfResearch.Gate6.Moments.Numeric.uniform_history_mean_bound
#print axioms SigGolfResearch.Gate6.Moments.Numeric.uniform_history_excess_bound
#print axioms SigGolfResearch.Gate6.Moments.Numeric.uniform_history_near_bound
#print axioms SigGolfResearch.Gate6.gatedDraw_card
#print axioms SigGolfResearch.Gate6.raw_draw_event
#print axioms SigGolfResearch.Gate6.gated_covered_probability
#print axioms SigGolfResearch.Gate6.digest_gate_covered_probability
#print axioms SigGolfResearch.Gate6.accepted_covered_le_gate
#print axioms SigGolfResearch.Gate6.accepted_covered_le_forestEnvelope
#print axioms SigGolfResearch.Gate6.Source.sortedChild_nodup
#print axioms SigGolfResearch.Gate6.Source.sortedChild_length
#print axioms SigGolfResearch.Gate6.Source.sortedChild_eq
#print axioms SigGolfResearch.Gate6.Source.authCount_eq_octH
#print axioms SigGolfResearch.Gate6.Source.source_child_auth
#print axioms SigGolfResearch.Gate6.Source.source_selections
#print axioms SigGolfResearch.Gate6.Source.source_leaf_condition
#print axioms SigGolfResearch.Gate6.Source.actual_predicate_iff
#print axioms SigGolfResearch.Gate6.Source.actual_acceptance_exact
#print axioms SigGolfResearch.Gate6.Source.actual_mark_joint_exact
#print axioms SigGolfResearch.Gate6.Source.actual_accepted_mark_weight
#print axioms SigGolfCandidate.T3.DigestSampling.coordinates_injective
#print axioms SigGolfCandidate.T3.DigestSampling.coordinates_bijective
#print axioms SigGolfCandidate.T3.DigestSampling.uniform_coordinates
#print axioms SigGolfCandidate.T3.DigestSampling.rawView_index
#print axioms SigGolfCandidate.T3.DigestSampling.rawView_bucket
#print axioms SigGolfCandidate.T3.DigestSampling.rawView_leaf
#print axioms SigGolfCandidate.T3.DigestSampling.rawSelections_eq_selections
#print axioms SigGolfCandidate.T3.DigestSampling.raw_admissible
#print axioms SigGolfCandidate.T3.DigestSampling.source_admissible
#print axioms SigGolfCandidate.T3.DigestSampling.uniform_samplingData
#print axioms SigGolfCandidate.T3.DigestSampling.samplingData_expectedValue
#print axioms SigGolfCandidate.T3.DigestSampling.finiteAverage_mul_const
#print axioms SigGolfCandidate.T3.DigestSampling.finiteAverage_const_mul
#print axioms SigGolfCandidate.T3.DigestSampling.finiteAverage_pair_product
#print axioms SigGolfCandidate.T3.DigestSampling.samplingData_mark
#print axioms SigGolfCandidate.T3.DigestSampling.accepted_samplingData
#print axioms SigGolfCandidate.T3.DigestSampling.fresh_digest_coordinates
#print axioms SigGolfCandidate.T3.DigestSampling.digest_trial_inputs_injective
