-- Generated by scouts/t3-rl2/gen_expand_blocks_rl2.py from T3M/Images/Expand.lean (n3-99). Do not edit.
import SigGolfCandidate.T3M.Search.Blocks

/-!
# `expand`: segments, placements and symbolic blocks (stream E)

* the segments `seg_i` of the expand image outside the digest-search loop [30, 49) (`Search.dsL 30`) and the
  shared kernel [354, 824) (`Search.kernCode`), placed by `codeAt_i`, run by `eblk_i` (`noAlias`);
* `expL` / `code_eq` : the image is the layout of these pieces (kernel check); `kernAt_expand`, `dsAt_expand`
  (in `Search.Blocks`) give the kernel and the loop.
-/

namespace SigGolfCandidate.T3M.Expand
open RiscvZkvm.Rv64 SigGolfCandidate.Legacy SigGolfCandidate.Legacy.Riscv SigGolfCandidate.Rv

set_option maxRecDepth 16384
set_option linter.unusedVariables false

/-! ## Segments -/

def seg_0 : List (BitVec 32) := [0x00000293, 0x00007eb7, 0x00001f37, 0x800f0f13, 0x000eb303, 0x008eb383, 0x006f3023, 0x007f3423, 0x00007eb7, 0x00020f37, 0x120f0f13, 0x000eb303, 0x008eb383, 0x006f3023, 0x007f3423, 0x04000e93, 0x00020f37, 0x140f0f13, 0x000eb303, 0x008eb383, 0x006f3023, 0x007f3423, 0x05000e93, 0x00020f37, 0x150f0f13, 0x000eb303, 0x008eb383, 0x006f3023, 0x007f3423, 0x00000993]
def seg_49 : List (BitVec 32) := [0x00020e37, 0x160e0e13, 0x000e3483, 0x02149493, 0x0214d493, 0x00020e37, 0x550e0e13, 0x009e3023, 0x00001e37, 0x810e0e13, 0x013e2023, 0x00022137, 0x00000913, 0x00001b37, 0xc40b0b13, 0x00000413]
def seg_65 : List (BitVec 32) := [0x00700313, 0x24645a63]
def seg_67 : List (BitVec 32) := [0x00000993]
def seg_68 : List (BitVec 32) := [0x00300313, 0x0469d863]
def seg_70 : List (BitVec 32) := [0x00141713, 0x00870733, 0x01370733, 0x00471e13, 0x00007eb7, 0x010e8e93, 0x01de0e33, 0x00571693, 0x00471713, 0x00e686b3, 0x00001eb7, 0x860e8e93, 0x01d686b3, 0x000e3303, 0x008e3383, 0x0066b023, 0x0076b423, 0x00198993, 0xfb1ff06f]
def seg_89 : List (BitVec 32) := [0x00441713, 0x00341e13, 0x01c70733, 0x00020e37, 0x4a0e0e13, 0x01c70733, 0x00073583, 0x0075d593, 0x00700513, 0x359000ef]
def seg_99 : List (BitVec 32) := [0x00000993]
def seg_100 : List (BitVec 32) := [0x00400313, 0x1669d863]
def seg_102 : List (BitVec 32) := [0x07300313, 0x3e695663]
def seg_104 : List (BitVec 32) := [0x00491693, 0x00007e37, 0x160e0e13, 0x01c686b3, 0x00190913, 0x00441713, 0x00341e13, 0x01c70733, 0x00020e37, 0x4a0e0e13, 0x01c70733, 0x00073703, 0x00775713, 0x01375e33, 0x001e7e13, 0x060e0263]
def seg_120 : List (BitVec 32) := [0x00020f37, 0x200f0f13, 0x0006b303, 0x0086b383, 0x006f3023, 0x007f3423, 0x00020eb7, 0x240e8e93, 0x00020f37, 0x230f0f13, 0x000eb303, 0x008eb383, 0x006f3023, 0x007f3423, 0x006b9e13, 0x004b9f13, 0x01ee0e33, 0x016e0e33, 0x0006b303, 0x0086b383, 0x006e3423, 0x007e3823, 0x001b8b93, 0x0600006f]
def seg_144 : List (BitVec 32) := [0x00020eb7, 0x240e8e93, 0x00020f37, 0x200f0f13, 0x000eb303, 0x008eb383, 0x006f3023, 0x007f3423, 0x00020f37, 0x230f0f13, 0x0006b303, 0x0086b383, 0x006f3023, 0x007f3423, 0x006b9e13, 0x004b9f13, 0x01ee0e33, 0x016e0e33, 0x0006b303, 0x0086b383, 0x026e3c23, 0x047e3023, 0x001b8b93]
def seg_167 : List (BitVec 32) := [0x00300e13, 0x413e0e33, 0x00100693, 0x01c696b3, 0x00198e13, 0x01c75e33, 0x01c686b3, 0x00001337, 0xa0130313, 0x01041f13, 0x01e36333, 0x7610006f]
def seg_179 : List (BitVec 32) := [0x02049f13, 0x01e36333, 0x00020e37, 0x200e0e13, 0x006e3823, 0x007e3c23, 0x00020537, 0x20050513, 0x04000593, 0x00020637, 0x24060613]
def seg_190 : List (BitVec 32) := [0x00000073]
def seg_191 : List (BitVec 32) := [0x00198993, 0xe91ff06f]
def seg_193 : List (BitVec 32) := [0x005c1e13, 0x017e6e33, 0x01cb0023, 0x006b9e13, 0x004b9f13, 0x01ee0e33, 0x01cb0b33, 0x008b0b13, 0x00441e13, 0x00040463]
def seg_203 : List (BitVec 32) := [0x010e0e13]
def seg_204 : List (BitVec 32) := [0x00020eb7, 0x320e8e93, 0x01de0e33, 0x00020eb7, 0x240e8e93, 0x000eb303, 0x008eb383, 0x006e3023, 0x007e3423, 0x00140413, 0xdadff06f]
def seg_215 : List (BitVec 32) := [0x00090693]
def seg_216 : List (BitVec 32) := [0x07300313, 0x0266d663]
def seg_218 : List (BitVec 32) := [0x00469e13, 0x00007eb7, 0x160e8e93, 0x01de0e33, 0x000e3303, 0x20031663]
def seg_224 : List (BitVec 32) := [0x008e3303, 0x20031263]
def seg_226 : List (BitVec 32) := [0x00168693, 0xfd5ff06f]
def seg_228 : List (BitVec 32) := [0x00001337, 0xb0130313, 0x00048393, 0x00020e37, 0x320e0e13, 0x006e3823, 0x007e3c23, 0x00020537, 0x32050513, 0x08000593, 0x00020637, 0x3a060613]
def seg_240 : List (BitVec 32) := [0x00000073]
def seg_241 : List (BitVec 32) := [0x00020eb7, 0x3a0e8e93, 0x00020f37, 0x260f0f13, 0x000eb303, 0x008eb383, 0x006f3023, 0x007f3423]
def seg_249 : List (BitVec 32) := [0x00300413, 0x00600793, 0x02b00d13, 0x00000d93, 0x0c300893, 0x00020e37, 0x550e0e13, 0x000e3303, 0x00035393, 0x03f00e13, 0x01c3f933, 0x00635493, 0x310000ef]
def seg_262 : List (BitVec 32) := [0x00001e37, 0x820e0e13, 0x013e2023, 0x00008837, 0x2e080813, 0x00007bb7, 0xa58b8b93, 0x00006c37, 0xf98c0c13, 0x359000ef]
def seg_272 : List (BitVec 32) := [0x00200413, 0x00600793, 0x02b00d13, 0x00000d93, 0x0c300893, 0x00020e37, 0x550e0e13, 0x000e3303, 0x00635393, 0x03f00e13, 0x01c3f933, 0x00c35493, 0x2b4000ef]
def seg_285 : List (BitVec 32) := [0x00001e37, 0x81ce0e13, 0x013e2023, 0x00008837, 0xfd080813, 0x00006bb7, 0xe18b8b93, 0x00005c37, 0x358c0c13, 0x2fd000ef]
def seg_295 : List (BitVec 32) := [0x00100413, 0x00700793, 0x02b00d13, 0x00000d93, 0x0c300893, 0x00020e37, 0x550e0e13, 0x000e3303, 0x00c35393, 0x07f00e13, 0x01c3f933, 0x01335493, 0x258000ef]
def seg_308 : List (BitVec 32) := [0x00001e37, 0x818e0e13, 0x013e2023, 0x00008837, 0xcb080813, 0x00005bb7, 0x1d8b8b93, 0x00004c37, 0x718c0c13, 0x2a1000ef]
def seg_318 : List (BitVec 32) := [0x00000413, 0x00c00793, 0x03600d13, 0x03300d93, 0x07e00893, 0x00020e37, 0x550e0e13, 0x000e3303, 0x01335393, 0x00001e37, 0xfffe0e13, 0x01c3f933, 0x01f35493, 0x1f8000ef]
def seg_332 : List (BitVec 32) := [0x00001e37, 0x814e0e13, 0x013e2023, 0x00008837, 0x89080813, 0x00004bb7, 0x458b8b93, 0x00003c37, 0x6d8c0c13, 0x241000ef]
def seg_342 : List (BitVec 32) := [0x00020e37, 0x240e0e13, 0x0a000e93, 0x000e3303, 0x000eb383, 0x00731e63]
def seg_348 : List (BitVec 32) := [0x008e3303, 0x008eb383, 0x00731863]
def seg_351 : List (BitVec 32) := [0x00100293, 0x00000513]
def seg_353 : List (BitVec 32) := [0x00000073]
def seg_824 : List (BitVec 32) := [0xfd010113, 0x00113023, 0x00a13423, 0x00b13823, 0x00441713, 0x00341e13, 0x01c70733, 0x00020e37, 0x4a0e0e13, 0x01c70733, 0x00000a13]
def seg_835 : List (BitVec 32) := [0x003a1e13, 0x00ee0e33, 0x000e3e83, 0x00aedf33, 0x04bf0663]
def seg_840 : List (BitVec 32) := [0x001a0a13, 0x00300e13, 0xffca12e3]
def seg_843 : List (BitVec 32) := [0x07300e13, 0x85c95ce3]
def seg_845 : List (BitVec 32) := [0x00491e13, 0x00007eb7, 0x160e8e93, 0x01de0e33, 0x00020f37, 0x240f0f13, 0x000e3303, 0x008e3383, 0x006f3023, 0x007f3423, 0x00190913, 0x00000513, 0x2240006f]
def seg_858 : List (BitVec 32) := [0x0a051863]
def seg_859 : List (BitVec 32) := [0x020a0263]
def seg_860 : List (BitVec 32) := [0x005c1e13, 0x017e6e33, 0x01cb0023, 0x006b9e13, 0x004b9f13, 0x01ee0e33, 0x01cb0b33, 0x008b0b13]
def seg_868 : List (BitVec 32) := [0x00000b93, 0x007efc13, 0x00141713, 0x00870733, 0x01470733, 0x00471713, 0x00007e37, 0x010e0e13, 0x01c70733, 0x00020f37, 0x2e0f0f13, 0x00073303, 0x00873383, 0x006f3023, 0x007f3423, 0x00001337, 0x90130313, 0x01041f13, 0x01e36333, 0x52c0006f]
def seg_888 : List (BitVec 32) := [0x02049f13, 0x01e36333, 0x00020e37, 0x2c0e0e13, 0x006e3823, 0x007e3c23, 0x00020537, 0x2c050513, 0x04000593, 0x00020637, 0x24060613]
def seg_899 : List (BitVec 32) := [0x00000073]
def seg_900 : List (BitVec 32) := [0x00100513, 0x1740006f]
def seg_902 : List (BitVec 32) := [0xfff50513, 0x00159593, 0xec1ff0ef]
def seg_905 : List (BitVec 32) := [0x00a13c23, 0x00020eb7, 0x240e8e93, 0x000eb303, 0x008eb383, 0x02613023, 0x02713423, 0x00813503, 0x01013583, 0xfff50513, 0x00159593, 0x00158593, 0xe8dff0ef]
def seg_918 : List (BitVec 32) := [0x00020f37, 0x200f0f13, 0x02013303, 0x02813383, 0x006f3023, 0x007f3423, 0x00020eb7, 0x240e8e93, 0x00020f37, 0x230f0f13, 0x000eb303, 0x008eb383, 0x006f3023, 0x007f3423, 0x00813e03, 0x00b00693, 0x41c686b3, 0x00100e13, 0x00de16b3, 0x01013e03, 0x01c686b3, 0x00001337, 0xa0130313, 0x01041f13, 0x01e36333, 0x3dc0006f]
def seg_944 : List (BitVec 32) := [0x02049f13, 0x01e36333, 0x00020e37, 0x200e0e13, 0x006e3823, 0x007e3c23, 0x01813e03, 0x020e1663]
def seg_952 : List (BitVec 32) := [0x006b9e13, 0x004b9f13, 0x01ee0e33, 0x016e0e33, 0x02013303, 0x02813383, 0x006e3423, 0x007e3823, 0x001b8b93, 0x0680006f]
def seg_962 : List (BitVec 32) := [0x02051a63]
def seg_963 : List (BitVec 32) := [0x006b9e13, 0x004b9f13, 0x01ee0e33, 0x016e0e33, 0x00020eb7, 0x240e8e93, 0x000eb303, 0x008eb383, 0x026e3c23, 0x047e3023, 0x001b8b93, 0x0340006f]
def seg_975 : List (BitVec 32) := [0x005c1e13, 0x017e6e33, 0x010e6e13, 0x01cb0023, 0x006b9e13, 0x004b9f13, 0x01ee0e33, 0x01cb0b33, 0x008b0b13, 0x00000b93, 0x01013e03, 0x007e7c13]
def seg_987 : List (BitVec 32) := [0x00020537, 0x20050513, 0x04000593, 0x00020637, 0x24060613]
def seg_992 : List (BitVec 32) := [0x00000073]
def seg_993 : List (BitVec 32) := [0x00100513]
def seg_994 : List (BitVec 32) := [0x00013083, 0x03010113, 0x00008067]
def seg_997 : List (BitVec 32) := [0x00048393, 0x02091f13, 0x01e3e3b3, 0x00020e37, 0x1a0e0e13, 0x007e3c23, 0x00020e37, 0x600e0e13, 0x007e3c23, 0x01041313, 0x20136313, 0x006e3823, 0x00000993]
def seg_1010 : List (BitVec 32) := [0x0da9da63]
def seg_1011 : List (BitVec 32) := [0x00499e13, 0x010e0e33, 0x00020f37, 0x1d0f0f13, 0x000e3303, 0x008e3383, 0x006f3023, 0x007f3423, 0x000e3303, 0x008e3383, 0x026bb823, 0x027bbc23, 0xfc0b8b93, 0x00020e37, 0x420e0e13, 0x013e0e33]
def seg_1027 : List (BitVec 32) := [0x000e4a03]
def seg_1028 : List (BitVec 32) := [0x00700a93, 0x00041463]
def seg_1030 : List (BitVec 32) := [0x2000006f]
def seg_1031 : List (BitVec 32) := [0x055a5463]
def seg_1032 : List (BitVec 32) := [0x00899393, 0x014383b3, 0x02039313, 0x01041f13, 0x01e36333, 0x10136313, 0x00020e37, 0x1a0e0e13, 0x006e3823, 0x00020537, 0x1a050513, 0x04000593, 0x00020637, 0x1d060613]
def seg_1046 : List (BitVec 32) := [0x00000073]
def seg_1047 : List (BitVec 32) := [0x001a0a13, 0xfbdff06f]
def seg_1049 : List (BitVec 32) := [0x00499e13, 0x00098463]
def seg_1051 : List (BitVec 32) := [0x010e0e13]
def seg_1052 : List (BitVec 32) := [0x00020eb7, 0x600e8e93, 0x01de0e33, 0x00020eb7, 0x1d0e8e93, 0x000eb303, 0x008eb383, 0x006e3023, 0x007e3423, 0x00198993, 0xf31ff06f]
def seg_1063 : List (BitVec 32) := [0x001d0313, 0x00431313, 0x03f30313, 0xfc037313, 0x00020537, 0x60050513, 0x00030593, 0x00020637, 0x24060613]
def seg_1072 : List (BitVec 32) := [0x00000073]
def seg_1073 : List (BitVec 32) := [0x00000a13, 0x004d1e13, 0x01c80b33]
def seg_1076 : List (BitVec 32) := [0x10fa5663]
def seg_1077 : List (BitVec 32) := [0x01495e33, 0x001e7e13, 0x040e0863]
def seg_1080 : List (BitVec 32) := [0x000b3303, 0x008b3383, 0x006c3023, 0x007c3423, 0x00020f37, 0x200f0f13, 0x000b3303, 0x008b3383, 0x006f3023, 0x007f3423, 0x00020eb7, 0x240e8e93, 0x00020f37, 0x230f0f13, 0x000eb303, 0x008eb383, 0x006f3023, 0x007f3423, 0x04c0006f]
def seg_1099 : List (BitVec 32) := [0x000b3303, 0x008b3383, 0x026c3823, 0x027c3c23, 0x00020eb7, 0x240e8e93, 0x00020f37, 0x200f0f13, 0x000eb303, 0x008eb383, 0x006f3023, 0x007f3423, 0x00020f37, 0x230f0f13, 0x000b3303, 0x008b3383, 0x006f3023, 0x007f3423]
def seg_1117 : List (BitVec 32) := [0x41478e33, 0xfffe0e13, 0x00100693, 0x01c696b3, 0x001a0e13, 0x01c95e33, 0x01c686b3, 0x01041313, 0x30136313, 0x00068393, 0x02049f13, 0x01e36333, 0x00020e37, 0x200e0e13, 0x006e3823, 0x007e3c23, 0x00020537, 0x20050513, 0x04000593, 0x00020637, 0x24060613]
def seg_1138 : List (BitVec 32) := [0x00000073]
def seg_1139 : List (BitVec 32) := [0x010b0b13, 0xfc0c0c13, 0x001a0a13, 0xef9ff06f]
def seg_1143 : List (BitVec 32) := [0x00020eb7, 0x200e8e93, 0x00020f37, 0x260f0f13, 0x000eb303, 0x008eb383, 0x006f3023, 0x007f3423, 0x1800006f]

def seg_1152 : List (BitVec 32) := [0x00020337, 0x17833303, 0x03635313, 0x08733313, 0xd0030663, 0xb80ff06f]

def seg_1158 : List (BitVec 32) := [0x00300a93, 0xe1b9d0e3]
def seg_1160 : List (BitVec 32) := [0x00400a93, 0xdf9ff06f]
def seg_1162 : List (BitVec 32) := [0x00068393, 0x0ff3ff13, 0x008f1f13, 0x0083d393, 0x01e3e3b3, 0x00001e37, 0xf0fe0e13, 0x01c3ff33, 0x004f1f13, 0x0043d393, 0x01c3f3b3, 0x01e3e3b3, 0x00003e37, 0x333e0e13, 0x01c3ff33, 0x002f1f13, 0x0023d393, 0x01c3f3b3, 0x01e3e3b3, 0x00005e37, 0x555e0e13, 0x01c3ff33, 0x001f1f13, 0x0013d393, 0x01c3f3b3, 0x01e3e3b3, 0x03039393, 0x838ff06f]
def seg_1190 : List (BitVec 32) := [0x00068393, 0x0ff3ff13, 0x008f1f13, 0x0083d393, 0x01e3e3b3, 0x00001e37, 0xf0fe0e13, 0x01c3ff33, 0x004f1f13, 0x0043d393, 0x01c3f3b3, 0x01e3e3b3, 0x00003e37, 0x333e0e13, 0x01c3ff33, 0x002f1f13, 0x0023d393, 0x01c3f3b3, 0x01e3e3b3, 0x00005e37, 0x555e0e13, 0x01c3ff33, 0x001f1f13, 0x0013d393, 0x01c3f3b3, 0x01e3e3b3, 0x03039393, 0xbbdff06f]
def seg_1218 : List (BitVec 32) := [0x400e8393, 0x40038393, 0x0ff3ff13, 0x008f1f13, 0x0083d393, 0x01e3e3b3, 0x00001e37, 0xf0fe0e13, 0x01c3ff33, 0x004f1f13, 0x0043d393, 0x01c3f3b3, 0x01e3e3b3, 0x00003e37, 0x333e0e13, 0x01c3ff33, 0x002f1f13, 0x0023d393, 0x01c3f3b3, 0x01e3e3b3, 0x00005e37, 0x555e0e13, 0x01c3ff33, 0x001f1f13, 0x0013d393, 0x01c3f3b3, 0x01e3e3b3, 0x03039393, 0xa69ff06f]

def seg_1247 : List (BitVec 32) := [0x030eb303, 0x038eb383, 0x026f3823, 0x027f3c23, 0x00008067]

/-- The expand image as a layout. -/
def expL : Rv.Layout := [(0, seg_0), (30, layoutCode (Search.dsL 30)), (49, seg_49), (65, seg_65), (67, seg_67), (68, seg_68), (70, seg_70), (89, seg_89), (99, seg_99), (100, seg_100), (102, seg_102), (104, seg_104), (120, seg_120), (144, seg_144), (167, seg_167), (179, seg_179), (190, seg_190), (191, seg_191), (193, seg_193), (203, seg_203), (204, seg_204), (215, seg_215), (216, seg_216), (218, seg_218), (224, seg_224), (226, seg_226), (228, seg_228), (240, seg_240), (241, seg_241), (249, seg_249), (262, seg_262), (272, seg_272), (285, seg_285), (295, seg_295), (308, seg_308), (318, seg_318), (332, seg_332), (342, seg_342), (348, seg_348), (351, seg_351), (353, seg_353), (354, Search.kernCode), (824, seg_824), (835, seg_835), (840, seg_840), (843, seg_843), (845, seg_845), (858, seg_858), (859, seg_859), (860, seg_860), (868, seg_868), (888, seg_888), (899, seg_899), (900, seg_900), (902, seg_902), (905, seg_905), (918, seg_918), (944, seg_944), (952, seg_952), (962, seg_962), (963, seg_963), (975, seg_975), (987, seg_987), (992, seg_992), (993, seg_993), (994, seg_994), (997, seg_997), (1010, seg_1010), (1011, seg_1011), (1027, seg_1027), (1028, seg_1028), (1030, seg_1030), (1031, seg_1031), (1032, seg_1032), (1046, seg_1046), (1047, seg_1047), (1049, seg_1049), (1051, seg_1051), (1052, seg_1052), (1063, seg_1063), (1072, seg_1072), (1073, seg_1073), (1076, seg_1076), (1077, seg_1077), (1080, seg_1080), (1099, seg_1099), (1117, seg_1117), (1138, seg_1138), (1139, seg_1139), (1143, seg_1143), (1152, seg_1152), (1158, seg_1158), (1160, seg_1160), (1162, seg_1162), (1190, seg_1190), (1218, seg_1218), (1247, seg_1247)]

theorem expL_ok : layoutOk 0 expL = true := by decide +kernel

/-- The expand image. -/
abbrev image : Image := Images.expandImage

theorem code_eq : image.code = layoutCode expL := by decide +kernel

theorem codeAt_0 : CodeAt image (pcOf 0) seg_0 :=
  codeAt_layout code_eq expL_ok (i := 0) (by kernel_rfl) (by decide)
theorem codeAt_49 : CodeAt image (pcOf 49) seg_49 :=
  codeAt_layout code_eq expL_ok (i := 2) (by kernel_rfl) (by decide)
theorem codeAt_65 : CodeAt image (pcOf 65) seg_65 :=
  codeAt_layout code_eq expL_ok (i := 3) (by kernel_rfl) (by decide)
theorem codeAt_67 : CodeAt image (pcOf 67) seg_67 :=
  codeAt_layout code_eq expL_ok (i := 4) (by kernel_rfl) (by decide)
theorem codeAt_68 : CodeAt image (pcOf 68) seg_68 :=
  codeAt_layout code_eq expL_ok (i := 5) (by kernel_rfl) (by decide)
theorem codeAt_70 : CodeAt image (pcOf 70) seg_70 :=
  codeAt_layout code_eq expL_ok (i := 6) (by kernel_rfl) (by decide)
theorem codeAt_89 : CodeAt image (pcOf 89) seg_89 :=
  codeAt_layout code_eq expL_ok (i := 7) (by kernel_rfl) (by decide)
theorem codeAt_99 : CodeAt image (pcOf 99) seg_99 :=
  codeAt_layout code_eq expL_ok (i := 8) (by kernel_rfl) (by decide)
theorem codeAt_100 : CodeAt image (pcOf 100) seg_100 :=
  codeAt_layout code_eq expL_ok (i := 9) (by kernel_rfl) (by decide)
theorem codeAt_102 : CodeAt image (pcOf 102) seg_102 :=
  codeAt_layout code_eq expL_ok (i := 10) (by kernel_rfl) (by decide)
theorem codeAt_104 : CodeAt image (pcOf 104) seg_104 :=
  codeAt_layout code_eq expL_ok (i := 11) (by kernel_rfl) (by decide)
theorem codeAt_120 : CodeAt image (pcOf 120) seg_120 :=
  codeAt_layout code_eq expL_ok (i := 12) (by kernel_rfl) (by decide)
theorem codeAt_144 : CodeAt image (pcOf 144) seg_144 :=
  codeAt_layout code_eq expL_ok (i := 13) (by kernel_rfl) (by decide)
theorem codeAt_167 : CodeAt image (pcOf 167) seg_167 :=
  codeAt_layout code_eq expL_ok (i := 14) (by kernel_rfl) (by decide)
theorem codeAt_179 : CodeAt image (pcOf 179) seg_179 :=
  codeAt_layout code_eq expL_ok (i := 15) (by kernel_rfl) (by decide)
theorem codeAt_190 : CodeAt image (pcOf 190) seg_190 :=
  codeAt_layout code_eq expL_ok (i := 16) (by kernel_rfl) (by decide)
theorem codeAt_191 : CodeAt image (pcOf 191) seg_191 :=
  codeAt_layout code_eq expL_ok (i := 17) (by kernel_rfl) (by decide)
theorem codeAt_193 : CodeAt image (pcOf 193) seg_193 :=
  codeAt_layout code_eq expL_ok (i := 18) (by kernel_rfl) (by decide)
theorem codeAt_203 : CodeAt image (pcOf 203) seg_203 :=
  codeAt_layout code_eq expL_ok (i := 19) (by kernel_rfl) (by decide)
theorem codeAt_204 : CodeAt image (pcOf 204) seg_204 :=
  codeAt_layout code_eq expL_ok (i := 20) (by kernel_rfl) (by decide)
theorem codeAt_215 : CodeAt image (pcOf 215) seg_215 :=
  codeAt_layout code_eq expL_ok (i := 21) (by kernel_rfl) (by decide)
theorem codeAt_216 : CodeAt image (pcOf 216) seg_216 :=
  codeAt_layout code_eq expL_ok (i := 22) (by kernel_rfl) (by decide)
theorem codeAt_218 : CodeAt image (pcOf 218) seg_218 :=
  codeAt_layout code_eq expL_ok (i := 23) (by kernel_rfl) (by decide)
theorem codeAt_224 : CodeAt image (pcOf 224) seg_224 :=
  codeAt_layout code_eq expL_ok (i := 24) (by kernel_rfl) (by decide)
theorem codeAt_226 : CodeAt image (pcOf 226) seg_226 :=
  codeAt_layout code_eq expL_ok (i := 25) (by kernel_rfl) (by decide)
theorem codeAt_228 : CodeAt image (pcOf 228) seg_228 :=
  codeAt_layout code_eq expL_ok (i := 26) (by kernel_rfl) (by decide)
theorem codeAt_240 : CodeAt image (pcOf 240) seg_240 :=
  codeAt_layout code_eq expL_ok (i := 27) (by kernel_rfl) (by decide)
theorem codeAt_241 : CodeAt image (pcOf 241) seg_241 :=
  codeAt_layout code_eq expL_ok (i := 28) (by kernel_rfl) (by decide)
theorem codeAt_249 : CodeAt image (pcOf 249) seg_249 :=
  codeAt_layout code_eq expL_ok (i := 29) (by kernel_rfl) (by decide)
theorem codeAt_262 : CodeAt image (pcOf 262) seg_262 :=
  codeAt_layout code_eq expL_ok (i := 30) (by kernel_rfl) (by decide)
theorem codeAt_272 : CodeAt image (pcOf 272) seg_272 :=
  codeAt_layout code_eq expL_ok (i := 31) (by kernel_rfl) (by decide)
theorem codeAt_285 : CodeAt image (pcOf 285) seg_285 :=
  codeAt_layout code_eq expL_ok (i := 32) (by kernel_rfl) (by decide)
theorem codeAt_295 : CodeAt image (pcOf 295) seg_295 :=
  codeAt_layout code_eq expL_ok (i := 33) (by kernel_rfl) (by decide)
theorem codeAt_308 : CodeAt image (pcOf 308) seg_308 :=
  codeAt_layout code_eq expL_ok (i := 34) (by kernel_rfl) (by decide)
theorem codeAt_318 : CodeAt image (pcOf 318) seg_318 :=
  codeAt_layout code_eq expL_ok (i := 35) (by kernel_rfl) (by decide)
theorem codeAt_332 : CodeAt image (pcOf 332) seg_332 :=
  codeAt_layout code_eq expL_ok (i := 36) (by kernel_rfl) (by decide)
theorem codeAt_342 : CodeAt image (pcOf 342) seg_342 :=
  codeAt_layout code_eq expL_ok (i := 37) (by kernel_rfl) (by decide)
theorem codeAt_348 : CodeAt image (pcOf 348) seg_348 :=
  codeAt_layout code_eq expL_ok (i := 38) (by kernel_rfl) (by decide)
theorem codeAt_351 : CodeAt image (pcOf 351) seg_351 :=
  codeAt_layout code_eq expL_ok (i := 39) (by kernel_rfl) (by decide)
theorem codeAt_353 : CodeAt image (pcOf 353) seg_353 :=
  codeAt_layout code_eq expL_ok (i := 40) (by kernel_rfl) (by decide)
theorem codeAt_824 : CodeAt image (pcOf 824) seg_824 :=
  codeAt_layout code_eq expL_ok (i := 42) (by kernel_rfl) (by decide)
theorem codeAt_835 : CodeAt image (pcOf 835) seg_835 :=
  codeAt_layout code_eq expL_ok (i := 43) (by kernel_rfl) (by decide)
theorem codeAt_840 : CodeAt image (pcOf 840) seg_840 :=
  codeAt_layout code_eq expL_ok (i := 44) (by kernel_rfl) (by decide)
theorem codeAt_843 : CodeAt image (pcOf 843) seg_843 :=
  codeAt_layout code_eq expL_ok (i := 45) (by kernel_rfl) (by decide)
theorem codeAt_845 : CodeAt image (pcOf 845) seg_845 :=
  codeAt_layout code_eq expL_ok (i := 46) (by kernel_rfl) (by decide)
theorem codeAt_858 : CodeAt image (pcOf 858) seg_858 :=
  codeAt_layout code_eq expL_ok (i := 47) (by kernel_rfl) (by decide)
theorem codeAt_859 : CodeAt image (pcOf 859) seg_859 :=
  codeAt_layout code_eq expL_ok (i := 48) (by kernel_rfl) (by decide)
theorem codeAt_860 : CodeAt image (pcOf 860) seg_860 :=
  codeAt_layout code_eq expL_ok (i := 49) (by kernel_rfl) (by decide)
theorem codeAt_868 : CodeAt image (pcOf 868) seg_868 :=
  codeAt_layout code_eq expL_ok (i := 50) (by kernel_rfl) (by decide)
theorem codeAt_888 : CodeAt image (pcOf 888) seg_888 :=
  codeAt_layout code_eq expL_ok (i := 51) (by kernel_rfl) (by decide)
theorem codeAt_899 : CodeAt image (pcOf 899) seg_899 :=
  codeAt_layout code_eq expL_ok (i := 52) (by kernel_rfl) (by decide)
theorem codeAt_900 : CodeAt image (pcOf 900) seg_900 :=
  codeAt_layout code_eq expL_ok (i := 53) (by kernel_rfl) (by decide)
theorem codeAt_902 : CodeAt image (pcOf 902) seg_902 :=
  codeAt_layout code_eq expL_ok (i := 54) (by kernel_rfl) (by decide)
theorem codeAt_905 : CodeAt image (pcOf 905) seg_905 :=
  codeAt_layout code_eq expL_ok (i := 55) (by kernel_rfl) (by decide)
theorem codeAt_918 : CodeAt image (pcOf 918) seg_918 :=
  codeAt_layout code_eq expL_ok (i := 56) (by kernel_rfl) (by decide)
theorem codeAt_944 : CodeAt image (pcOf 944) seg_944 :=
  codeAt_layout code_eq expL_ok (i := 57) (by kernel_rfl) (by decide)
theorem codeAt_952 : CodeAt image (pcOf 952) seg_952 :=
  codeAt_layout code_eq expL_ok (i := 58) (by kernel_rfl) (by decide)
theorem codeAt_962 : CodeAt image (pcOf 962) seg_962 :=
  codeAt_layout code_eq expL_ok (i := 59) (by kernel_rfl) (by decide)
theorem codeAt_963 : CodeAt image (pcOf 963) seg_963 :=
  codeAt_layout code_eq expL_ok (i := 60) (by kernel_rfl) (by decide)
theorem codeAt_975 : CodeAt image (pcOf 975) seg_975 :=
  codeAt_layout code_eq expL_ok (i := 61) (by kernel_rfl) (by decide)
theorem codeAt_987 : CodeAt image (pcOf 987) seg_987 :=
  codeAt_layout code_eq expL_ok (i := 62) (by kernel_rfl) (by decide)
theorem codeAt_992 : CodeAt image (pcOf 992) seg_992 :=
  codeAt_layout code_eq expL_ok (i := 63) (by kernel_rfl) (by decide)
theorem codeAt_993 : CodeAt image (pcOf 993) seg_993 :=
  codeAt_layout code_eq expL_ok (i := 64) (by kernel_rfl) (by decide)
theorem codeAt_994 : CodeAt image (pcOf 994) seg_994 :=
  codeAt_layout code_eq expL_ok (i := 65) (by kernel_rfl) (by decide)
theorem codeAt_997 : CodeAt image (pcOf 997) seg_997 :=
  codeAt_layout code_eq expL_ok (i := 66) (by kernel_rfl) (by decide)
theorem codeAt_1010 : CodeAt image (pcOf 1010) seg_1010 :=
  codeAt_layout code_eq expL_ok (i := 67) (by kernel_rfl) (by decide)
theorem codeAt_1011 : CodeAt image (pcOf 1011) seg_1011 :=
  codeAt_layout code_eq expL_ok (i := 68) (by kernel_rfl) (by decide)
theorem codeAt_1027 : CodeAt image (pcOf 1027) seg_1027 :=
  codeAt_layout code_eq expL_ok (i := 69) (by kernel_rfl) (by decide)
theorem codeAt_1028 : CodeAt image (pcOf 1028) seg_1028 :=
  codeAt_layout code_eq expL_ok (i := 70) (by kernel_rfl) (by decide)
theorem codeAt_1030 : CodeAt image (pcOf 1030) seg_1030 :=
  codeAt_layout code_eq expL_ok (i := 71) (by kernel_rfl) (by decide)
theorem codeAt_1031 : CodeAt image (pcOf 1031) seg_1031 :=
  codeAt_layout code_eq expL_ok (i := 72) (by kernel_rfl) (by decide)
theorem codeAt_1032 : CodeAt image (pcOf 1032) seg_1032 :=
  codeAt_layout code_eq expL_ok (i := 73) (by kernel_rfl) (by decide)
theorem codeAt_1046 : CodeAt image (pcOf 1046) seg_1046 :=
  codeAt_layout code_eq expL_ok (i := 74) (by kernel_rfl) (by decide)
theorem codeAt_1047 : CodeAt image (pcOf 1047) seg_1047 :=
  codeAt_layout code_eq expL_ok (i := 75) (by kernel_rfl) (by decide)
theorem codeAt_1049 : CodeAt image (pcOf 1049) seg_1049 :=
  codeAt_layout code_eq expL_ok (i := 76) (by kernel_rfl) (by decide)
theorem codeAt_1051 : CodeAt image (pcOf 1051) seg_1051 :=
  codeAt_layout code_eq expL_ok (i := 77) (by kernel_rfl) (by decide)
theorem codeAt_1052 : CodeAt image (pcOf 1052) seg_1052 :=
  codeAt_layout code_eq expL_ok (i := 78) (by kernel_rfl) (by decide)
theorem codeAt_1063 : CodeAt image (pcOf 1063) seg_1063 :=
  codeAt_layout code_eq expL_ok (i := 79) (by kernel_rfl) (by decide)
theorem codeAt_1072 : CodeAt image (pcOf 1072) seg_1072 :=
  codeAt_layout code_eq expL_ok (i := 80) (by kernel_rfl) (by decide)
theorem codeAt_1073 : CodeAt image (pcOf 1073) seg_1073 :=
  codeAt_layout code_eq expL_ok (i := 81) (by kernel_rfl) (by decide)
theorem codeAt_1076 : CodeAt image (pcOf 1076) seg_1076 :=
  codeAt_layout code_eq expL_ok (i := 82) (by kernel_rfl) (by decide)
theorem codeAt_1077 : CodeAt image (pcOf 1077) seg_1077 :=
  codeAt_layout code_eq expL_ok (i := 83) (by kernel_rfl) (by decide)
theorem codeAt_1080 : CodeAt image (pcOf 1080) seg_1080 :=
  codeAt_layout code_eq expL_ok (i := 84) (by kernel_rfl) (by decide)
theorem codeAt_1099 : CodeAt image (pcOf 1099) seg_1099 :=
  codeAt_layout code_eq expL_ok (i := 85) (by kernel_rfl) (by decide)
theorem codeAt_1117 : CodeAt image (pcOf 1117) seg_1117 :=
  codeAt_layout code_eq expL_ok (i := 86) (by kernel_rfl) (by decide)
theorem codeAt_1138 : CodeAt image (pcOf 1138) seg_1138 :=
  codeAt_layout code_eq expL_ok (i := 87) (by kernel_rfl) (by decide)
theorem codeAt_1139 : CodeAt image (pcOf 1139) seg_1139 :=
  codeAt_layout code_eq expL_ok (i := 88) (by kernel_rfl) (by decide)
theorem codeAt_1247 : CodeAt image (pcOf 1247) seg_1247 :=
  codeAt_layout code_eq expL_ok (i := 96) (by kernel_rfl) (by decide)
theorem codeAt_1143 : CodeAt image (pcOf 1143) seg_1143 :=
  codeAt_layout code_eq expL_ok (i := 89) (by kernel_rfl) (by decide)
theorem codeAt_1158 : CodeAt image (pcOf 1158) seg_1158 :=
  codeAt_layout code_eq expL_ok (i := 91) (by kernel_rfl) (by decide)
theorem codeAt_1160 : CodeAt image (pcOf 1160) seg_1160 :=
  codeAt_layout code_eq expL_ok (i := 92) (by kernel_rfl) (by decide)
theorem codeAt_1162 : CodeAt image (pcOf 1162) seg_1162 :=
  codeAt_layout code_eq expL_ok (i := 93) (by kernel_rfl) (by decide)
theorem codeAt_1190 : CodeAt image (pcOf 1190) seg_1190 :=
  codeAt_layout code_eq expL_ok (i := 94) (by kernel_rfl) (by decide)
theorem codeAt_1218 : CodeAt image (pcOf 1218) seg_1218 :=
  codeAt_layout code_eq expL_ok (i := 95) (by kernel_rfl) (by decide)

/-! ## Symbolic blocks -/

sym_block eblk_0 := symRun { noAlias := true } seg_0 (pcOf 0) 200
sym_block eblk_49 := symRun { noAlias := true } seg_49 (pcOf 49) 200
sym_block eblk_65 := symRun { noAlias := true } seg_65 (pcOf 65) 200
sym_block eblk_67 := symRun { noAlias := true } seg_67 (pcOf 67) 200
sym_block eblk_68 := symRun { noAlias := true } seg_68 (pcOf 68) 200
sym_block eblk_70 := symRun { noAlias := true } seg_70 (pcOf 70) 200
sym_block eblk_89 := symRun { noAlias := true } seg_89 (pcOf 89) 200
sym_block eblk_99 := symRun { noAlias := true } seg_99 (pcOf 99) 200
sym_block eblk_100 := symRun { noAlias := true } seg_100 (pcOf 100) 200
sym_block eblk_102 := symRun { noAlias := true } seg_102 (pcOf 102) 200
sym_block eblk_104 := symRun { noAlias := true } seg_104 (pcOf 104) 200
sym_block eblk_120 := symRun { noAlias := true } seg_120 (pcOf 120) 200
sym_block eblk_144 := symRun { noAlias := true } seg_144 (pcOf 144) 200
sym_block eblk_167 := symRun { noAlias := true } seg_167 (pcOf 167) 200
sym_block eblk_179 := symRun { noAlias := true } seg_179 (pcOf 179) 200
sym_block eblk_191 := symRun { noAlias := true } seg_191 (pcOf 191) 200
sym_block eblk_193 := symRun { noAlias := true } seg_193 (pcOf 193) 200
sym_block eblk_203 := symRun { noAlias := true } seg_203 (pcOf 203) 200
sym_block eblk_204 := symRun { noAlias := true } seg_204 (pcOf 204) 200
sym_block eblk_215 := symRun { noAlias := true } seg_215 (pcOf 215) 200
sym_block eblk_216 := symRun { noAlias := true } seg_216 (pcOf 216) 200
sym_block eblk_218 := symRun { noAlias := true } seg_218 (pcOf 218) 200
sym_block eblk_224 := symRun { noAlias := true } seg_224 (pcOf 224) 200
sym_block eblk_226 := symRun { noAlias := true } seg_226 (pcOf 226) 200
sym_block eblk_228 := symRun { noAlias := true } seg_228 (pcOf 228) 200
sym_block eblk_241 := symRun { noAlias := true } seg_241 (pcOf 241) 200
sym_block eblk_249 := symRun { noAlias := true } seg_249 (pcOf 249) 200
sym_block eblk_262 := symRun { noAlias := true } seg_262 (pcOf 262) 200
sym_block eblk_272 := symRun { noAlias := true } seg_272 (pcOf 272) 200
sym_block eblk_285 := symRun { noAlias := true } seg_285 (pcOf 285) 200
sym_block eblk_295 := symRun { noAlias := true } seg_295 (pcOf 295) 200
sym_block eblk_308 := symRun { noAlias := true } seg_308 (pcOf 308) 200
sym_block eblk_318 := symRun { noAlias := true } seg_318 (pcOf 318) 200
sym_block eblk_332 := symRun { noAlias := true } seg_332 (pcOf 332) 200
sym_block eblk_342 := symRun { noAlias := true } seg_342 (pcOf 342) 200
sym_block eblk_348 := symRun { noAlias := true } seg_348 (pcOf 348) 200
sym_block eblk_351 := symRun { noAlias := true } seg_351 (pcOf 351) 200
sym_block eblk_824 := symRun { noAlias := true } seg_824 (pcOf 824) 200
sym_block eblk_835 := symRun { noAlias := true } seg_835 (pcOf 835) 200
sym_block eblk_840 := symRun { noAlias := true } seg_840 (pcOf 840) 200
sym_block eblk_843 := symRun { noAlias := true } seg_843 (pcOf 843) 200
sym_block eblk_845 := symRun { noAlias := true } seg_845 (pcOf 845) 200
sym_block eblk_858 := symRun { noAlias := true } seg_858 (pcOf 858) 200
sym_block eblk_859 := symRun { noAlias := true } seg_859 (pcOf 859) 200
sym_block eblk_860 := symRun { noAlias := true } seg_860 (pcOf 860) 200
sym_block eblk_868 := symRun { noAlias := true } seg_868 (pcOf 868) 200
sym_block eblk_888 := symRun { noAlias := true } seg_888 (pcOf 888) 200
sym_block eblk_900 := symRun { noAlias := true } seg_900 (pcOf 900) 200
sym_block eblk_902 := symRun { noAlias := true } seg_902 (pcOf 902) 200
sym_block eblk_905 := symRun { noAlias := true } seg_905 (pcOf 905) 200
sym_block eblk_918 := symRun { noAlias := true } seg_918 (pcOf 918) 200
sym_block eblk_944 := symRun { noAlias := true } seg_944 (pcOf 944) 200
sym_block eblk_952 := symRun { noAlias := true } seg_952 (pcOf 952) 200
sym_block eblk_962 := symRun { noAlias := true } seg_962 (pcOf 962) 200
sym_block eblk_963 := symRun { noAlias := true } seg_963 (pcOf 963) 200
sym_block eblk_975 := symRun { noAlias := true } seg_975 (pcOf 975) 200
sym_block eblk_987 := symRun { noAlias := true } seg_987 (pcOf 987) 200
sym_block eblk_993 := symRun { noAlias := true } seg_993 (pcOf 993) 200
sym_block eblk_994 := symRun { noAlias := true } seg_994 (pcOf 994) 200
sym_block eblk_997 := symRun { noAlias := true } seg_997 (pcOf 997) 200
sym_block eblk_1010 := symRun { noAlias := true } seg_1010 (pcOf 1010) 200
sym_block eblk_1011 := symRun { noAlias := true } seg_1011 (pcOf 1011) 200
sym_block eblk_1027 := symRun { noAlias := true } seg_1027 (pcOf 1027) 200
sym_block eblk_1028 := symRun { noAlias := true } seg_1028 (pcOf 1028) 200
sym_block eblk_1030 := symRun { noAlias := true } seg_1030 (pcOf 1030) 200
sym_block eblk_1031 := symRun { noAlias := true } seg_1031 (pcOf 1031) 200
sym_block eblk_1032 := symRun { noAlias := true } seg_1032 (pcOf 1032) 200
sym_block eblk_1047 := symRun { noAlias := true } seg_1047 (pcOf 1047) 200
sym_block eblk_1049 := symRun { noAlias := true } seg_1049 (pcOf 1049) 200
sym_block eblk_1051 := symRun { noAlias := true } seg_1051 (pcOf 1051) 200
sym_block eblk_1052 := symRun { noAlias := true } seg_1052 (pcOf 1052) 200
sym_block eblk_1063 := symRun { noAlias := true } seg_1063 (pcOf 1063) 200
sym_block eblk_1073 := symRun { noAlias := true } seg_1073 (pcOf 1073) 200
sym_block eblk_1076 := symRun { noAlias := true } seg_1076 (pcOf 1076) 200
sym_block eblk_1077 := symRun { noAlias := true } seg_1077 (pcOf 1077) 200
sym_block eblk_1080 := symRun { noAlias := true } seg_1080 (pcOf 1080) 200
sym_block eblk_1099 := symRun { noAlias := true } seg_1099 (pcOf 1099) 200
sym_block eblk_1117 := symRun { noAlias := true } seg_1117 (pcOf 1117) 200
sym_block eblk_1139 := symRun { noAlias := true } seg_1139 (pcOf 1139) 200
sym_block eblk_1143 := symRun { noAlias := true } seg_1143 (pcOf 1143) 200
sym_block eblk_1247 := symRun { noAlias := true } seg_1247 (pcOf 1247) 200
sym_block eblk_1158 := symRun { noAlias := true } seg_1158 (pcOf 1158) 200
sym_block eblk_1160 := symRun { noAlias := true } seg_1160 (pcOf 1160) 200
sym_block eblk_1162 := symRun { noAlias := true } seg_1162 (pcOf 1162) 200
sym_block eblk_1190 := symRun { noAlias := true } seg_1190 (pcOf 1190) 200
sym_block eblk_1218 := symRun { noAlias := true } seg_1218 (pcOf 1218) 200

end SigGolfCandidate.T3M.Expand
