-- Generated by gen/gen_expand_lean.py. Do not edit.
import SigGolfCandidate.Expand.Code

namespace SigGolfCandidate.Expand
open SigGolfCandidate.Legacy SigGolfCandidate.Legacy.Riscv RiscvZkvm.Rv64 SigGolfCandidate.Rv

/-! Symbolic blocks of the expand program (the word-copy loop bodies are handled by `Copy.lean`;
316 .. 381 are the sign's blocks `Sign.blkN`). -/

sym_block blk0 := symRun { noAlias := true } seg0 (pcOf 0) 15
sym_block blk14 := symRun { noAlias := true } seg14 (pcOf 14) 5
sym_block blk18 := symRun { noAlias := true } seg18 (pcOf 18) 8
sym_block blk25 := symRun { noAlias := true } seg25 (pcOf 25) 6
sym_block blk30 := symRun { noAlias := true } seg30 (pcOf 30) 11
sym_block blk40 := symRun { noAlias := true } seg40 (pcOf 40) 2
sym_block blk41 := symRun { noAlias := true } seg41 (pcOf 41) 4
sym_block blk44 := symRun { noAlias := true } seg44 (pcOf 44) 3
sym_block blk46 := symRun { noAlias := true } seg46 (pcOf 46) 3
sym_block blk48 := symRun { noAlias := true } seg48 (pcOf 48) 4
sym_block blk51 := symRun { noAlias := true } seg51 (pcOf 51) 5
sym_block blk55 := symRun { noAlias := true } seg55 (pcOf 55) 3
sym_block blk57 := symRun { noAlias := true } seg57 (pcOf 57) 8
sym_block blk64 := symRun { noAlias := true } seg64 (pcOf 64) 4
sym_block blk67 := symRun { noAlias := true } seg67 (pcOf 67) 4
sym_block blk70 := symRun { noAlias := true } seg70 (pcOf 70) 3
sym_block blk72 := symRun { noAlias := true } seg72 (pcOf 72) 10
sym_block blk81 := symRun { noAlias := true } seg81 (pcOf 81) 8
sym_block blk88 := symRun { noAlias := true } seg88 (pcOf 88) 4
sym_block blk91 := symRun { noAlias := true } seg91 (pcOf 91) 5
sym_block blk95 := symRun { noAlias := true } seg95 (pcOf 95) 2
sym_block blk96 := symRun { noAlias := true } seg96 (pcOf 96) 3
sym_block blk98 := symRun { noAlias := true } seg98 (pcOf 98) 12
sym_block blk109 := symRun { noAlias := true } seg109 (pcOf 109) 9
sym_block blk117 := symRun { noAlias := true } seg117 (pcOf 117) 3
sym_block blk119 := symRun { noAlias := true } seg119 (pcOf 119) 8
sym_block blk126 := symRun { noAlias := true } seg126 (pcOf 126) 4
sym_block blk129 := symRun { noAlias := true } seg129 (pcOf 129) 4
sym_block blk132 := symRun { noAlias := true } seg132 (pcOf 132) 3
sym_block blk134 := symRun { noAlias := true } seg134 (pcOf 134) 2
sym_block blk135 := symRun { noAlias := true } seg135 (pcOf 135) 3
sym_block blk137 := symRun { noAlias := true } seg137 (pcOf 137) 3
sym_block blk139 := symRun { noAlias := true } seg139 (pcOf 139) 6
sym_block blk150 := symRun { noAlias := true } seg150 (pcOf 150) 4
sym_block blk153 := symRun { noAlias := true } seg153 (pcOf 153) 8
sym_block blk160 := symRun { noAlias := true } seg160 (pcOf 160) 6
sym_block blk171 := symRun { noAlias := true } seg171 (pcOf 171) 2
sym_block blk284 := symRun { noAlias := true } seg284 (pcOf 284) 4
sym_block blk382 := symRun { noAlias := true } seg382 (pcOf 382) 5
sym_block blk386 := symRun { noAlias := true } seg386 (pcOf 386) 23
sym_block blk408 := symRun { noAlias := true } seg408 (pcOf 408) 5
sym_block blk412 := symRun { noAlias := true } seg412 (pcOf 412) 2
sym_block blk413 := symRun { noAlias := true } seg413 (pcOf 413) 5
sym_block blk417 := symRun { noAlias := true } seg417 (pcOf 417) 3
sym_block blk419 := symRun { noAlias := true } seg419 (pcOf 419) 6
sym_block blk426 := symRun { noAlias := true } seg426 (pcOf 426) 3
sym_block blk428 := symRun { noAlias := true } seg428 (pcOf 428) 11
sym_block blk438 := symRun { noAlias := true } seg438 (pcOf 438) 5
sym_block blk442 := symRun { noAlias := true } seg442 (pcOf 442) 2
sym_block blk446 := symRun { noAlias := true } seg446 (pcOf 446) 11
sym_block blk456 := symRun { noAlias := true } seg456 (pcOf 456) 6
sym_block blk461 := symRun { noAlias := true } seg461 (pcOf 461) 5
sym_block blk465 := symRun { noAlias := true } seg465 (pcOf 465) 5
sym_block blk469 := symRun { noAlias := true } seg469 (pcOf 469) 4
sym_block blk472 := symRun { noAlias := true } seg472 (pcOf 472) 7
sym_block blk478 := symRun { noAlias := true } seg478 (pcOf 478) 18
sym_block blk495 := symRun { noAlias := true } seg495 (pcOf 495) 35
sym_block blk529 := symRun { noAlias := true } seg529 (pcOf 529) 5
sym_block blk533 := symRun { noAlias := true } seg533 (pcOf 533) 2
sym_block blk534 := symRun { noAlias := true } seg534 (pcOf 534) 3
sym_block blk536 := symRun { noAlias := true } seg536 (pcOf 536) 3
sym_block blk538 := symRun { noAlias := true } seg538 (pcOf 538) 13
sym_block blk550 := symRun { noAlias := true } seg550 (pcOf 550) 5
sym_block blk554 := symRun { noAlias := true } seg554 (pcOf 554) 2
sym_block blk555 := symRun { noAlias := true } seg555 (pcOf 555) 5
sym_block blk559 := symRun { noAlias := true } seg559 (pcOf 559) 3
sym_block blk561 := symRun { noAlias := true } seg561 (pcOf 561) 2
sym_block blk562 := symRun { noAlias := true } seg562 (pcOf 562) 4
sym_block blk565 := symRun { noAlias := true } seg565 (pcOf 565) 3
sym_block blk567 := symRun { noAlias := true } seg567 (pcOf 567) 2
sym_block blk568 := symRun { noAlias := true } seg568 (pcOf 568) 11
sym_block blk578 := symRun { noAlias := true } seg578 (pcOf 578) 6
sym_block blk583 := symRun { noAlias := true } seg583 (pcOf 583) 5
sym_block blk587 := symRun { noAlias := true } seg587 (pcOf 587) 5
sym_block blk591 := symRun { noAlias := true } seg591 (pcOf 591) 5
sym_block blk595 := symRun { noAlias := true } seg595 (pcOf 595) 8
sym_block blk602 := symRun { noAlias := true } seg602 (pcOf 602) 2
sym_block blk603 := symRun { noAlias := true } seg603 (pcOf 603) 4
sym_block blk606 := symRun { noAlias := true } seg606 (pcOf 606) 15
sym_block blk620 := symRun { noAlias := true } seg620 (pcOf 620) 3
sym_block blk622 := symRun { noAlias := true } seg622 (pcOf 622) 8
sym_block blk629 := symRun { noAlias := true } seg629 (pcOf 629) 5
sym_block blk633 := symRun { noAlias := true } seg633 (pcOf 633) 3
sym_block blk635 := symRun { noAlias := true } seg635 (pcOf 635) 3
sym_block blk637 := symRun { noAlias := true } seg637 (pcOf 637) 2
sym_block blk638 := symRun { noAlias := true } seg638 (pcOf 638) 2
sym_block blk639 := symRun { noAlias := true } seg639 (pcOf 639) 35
sym_block blk673 := symRun { noAlias := true } seg673 (pcOf 673) 11
sym_block blk683 := symRun { noAlias := true } seg683 (pcOf 683) 6
sym_block blk696 := symRun { noAlias := true } seg696 (pcOf 696) 6
sym_block blk707 := symRun { noAlias := true } seg707 (pcOf 707) 6
sym_block blk720 := symRun { noAlias := true } seg720 (pcOf 720) 6
sym_block blk731 := symRun { noAlias := true } seg731 (pcOf 731) 6
sym_block blk744 := symRun { noAlias := true } seg744 (pcOf 744) 6
sym_block blk755 := symRun { noAlias := true } seg755 (pcOf 755) 6
sym_block blk768 := symRun { noAlias := true } seg768 (pcOf 768) 6
sym_block blk779 := symRun { noAlias := true } seg779 (pcOf 779) 6
sym_block blk792 := symRun { noAlias := true } seg792 (pcOf 792) 6
sym_block blk803 := symRun { noAlias := true } seg803 (pcOf 803) 2

end SigGolfCandidate.Expand
