-- Generated by gen/gen_expand_lean.py. Do not edit.
import SigGolfCandidate.Expand.Code

namespace SigGolfCandidate.Expand
open SigGolfCandidate.Legacy SigGolfCandidate.Legacy.Riscv RiscvZkvm.Rv64 SigGolfCandidate.Rv

/-! Symbolic blocks of the expand program (the word-copy loop bodies are handled by `Copy.lean`;
316 .. 381 are the sign's blocks `Sign.blkN`). -/

sym_block blk0 := symRun { noAlias := true } seg0 (pcOf 0) 15
sym_block blk14 := symRun { noAlias := true } seg14 (pcOf 14) 5
sym_block blk18 := symRun { noAlias := true } seg18 (pcOf 18) 8
sym_block blk25 := symRun { noAlias := true } seg25 (pcOf 25) 6
sym_block blk30 := symRun { noAlias := true } seg30 (pcOf 30) 11
sym_block blk40 := symRun { noAlias := true } seg40 (pcOf 40) 2
sym_block blk41 := symRun { noAlias := true } seg41 (pcOf 41) 4
sym_block blk44 := symRun { noAlias := true } seg44 (pcOf 44) 3
sym_block blk46 := symRun { noAlias := true } seg46 (pcOf 46) 3
sym_block blk48 := symRun { noAlias := true } seg48 (pcOf 48) 4
sym_block blk51 := symRun { noAlias := true } seg51 (pcOf 51) 5
sym_block blk55 := symRun { noAlias := true } seg55 (pcOf 55) 3
sym_block blk57 := symRun { noAlias := true } seg57 (pcOf 57) 8
sym_block blk64 := symRun { noAlias := true } seg64 (pcOf 64) 4
sym_block blk67 := symRun { noAlias := true } seg67 (pcOf 67) 4
sym_block blk70 := symRun { noAlias := true } seg70 (pcOf 70) 3
sym_block blk72 := symRun { noAlias := true } seg72 (pcOf 72) 10
sym_block blk81 := symRun { noAlias := true } seg81 (pcOf 81) 8
sym_block blk88 := symRun { noAlias := true } seg88 (pcOf 88) 4
sym_block blk91 := symRun { noAlias := true } seg91 (pcOf 91) 5
sym_block blk95 := symRun { noAlias := true } seg95 (pcOf 95) 2
sym_block blk96 := symRun { noAlias := true } seg96 (pcOf 96) 3
sym_block blk98 := symRun { noAlias := true } seg98 (pcOf 98) 12
sym_block blk109 := symRun { noAlias := true } seg109 (pcOf 109) 9
sym_block blk117 := symRun { noAlias := true } seg117 (pcOf 117) 3
sym_block blk119 := symRun { noAlias := true } seg119 (pcOf 119) 8
sym_block blk126 := symRun { noAlias := true } seg126 (pcOf 126) 4
sym_block blk129 := symRun { noAlias := true } seg129 (pcOf 129) 4
sym_block blk132 := symRun { noAlias := true } seg132 (pcOf 132) 3
sym_block blk134 := symRun { noAlias := true } seg134 (pcOf 134) 2
sym_block blk135 := symRun { noAlias := true } seg135 (pcOf 135) 3
sym_block blk137 := symRun { noAlias := true } seg137 (pcOf 137) 3
sym_block blk139 := symRun { noAlias := true } seg139 (pcOf 139) 6
sym_block blk150 := symRun { noAlias := true } seg150 (pcOf 150) 4
sym_block blk153 := symRun { noAlias := true } seg153 (pcOf 153) 8
sym_block blk160 := symRun { noAlias := true } seg160 (pcOf 160) 6
sym_block blk173 := symRun { noAlias := true } seg173 (pcOf 173) 2
sym_block blk284 := symRun { noAlias := true } seg284 (pcOf 284) 4
sym_block blk382 := symRun { noAlias := true } seg382 (pcOf 382) 5
sym_block blkCarryHead386 := symRun { noAlias := true } seg386 (pcOf 386) 100
sym_block blkCarryTest386 := symRunAux { noAlias := true } segCarryTest386 (pcOf 2927) 100 blkCarryHead386.res.st
sym_block blkCarryLow386 := symRunAux { noAlias := true } segCarryLow386 (pcOf 2930) 100 blkCarryTest386.res.st
sym_block blkCarryHigh386 := symRunAux { noAlias := true } segCarryHigh386 (pcOf 2933) 100 blkCarryTest386.res.st
sym_block blk386low := symRunAux { noAlias := true } segCarryReturn386 (pcOf 392) 100 blkCarryLow386.res.st
sym_block blk386high := symRunAux { noAlias := true } segCarryReturn386 (pcOf 392) 100 blkCarryHigh386.res.st
sym_block blk408 := symRun { noAlias := true } seg408 (pcOf 408) 5
sym_block blk412 := symRun { noAlias := true } seg412 (pcOf 412) 2
sym_block blk413 := symRun { noAlias := true } seg413 (pcOf 413) 5
sym_block blk417 := symRun { noAlias := true } seg417 (pcOf 417) 3
sym_block blk419 := symRun { noAlias := true } seg419 (pcOf 419) 6
sym_block blk426 := symRun { noAlias := true } seg426 (pcOf 426) 3
sym_block blk428 := symRun { noAlias := true } seg428 (pcOf 428) 11
sym_block blk438 := symRun { noAlias := true } seg438 (pcOf 438) 5
sym_block blk442 := symRun { noAlias := true } seg442 (pcOf 442) 2
sym_block blk446 := symRun { noAlias := true } seg446 (pcOf 446) 11
sym_block blk456 := symRun { noAlias := true } seg456 (pcOf 456) 6
sym_block blk461 := symRun { noAlias := true } seg461 (pcOf 461) 5
sym_block blk465 := symRun { noAlias := true } seg465 (pcOf 465) 5
sym_block blk469 := symRun { noAlias := true } seg469 (pcOf 469) 4
sym_block blk472 := symRun { noAlias := true } seg472 (pcOf 472) 7
sym_block blk1820 := symRun { noAlias := true } seg1820 (pcOf 1820) 7
sym_block blk477 := symRun { noAlias := true } seg477 (pcOf 477) 2
sym_block blk478 := symRun { noAlias := true } seg478 (pcOf 478) 18
sym_block blk495 := symRun { noAlias := true } seg495 (pcOf 495) 35
sym_block blk529 := symRun { noAlias := true } seg529 (pcOf 529) 5
sym_block blk533 := symRun { noAlias := true } seg533 (pcOf 533) 2
sym_block blk534 := symRun { noAlias := true } seg534 (pcOf 534) 3
sym_block blk536 := symRun { noAlias := true } seg536 (pcOf 536) 3
sym_block blk538 := symRun { noAlias := true } seg538 (pcOf 538) 13
sym_block blk550 := symRun { noAlias := true } seg550 (pcOf 550) 5
sym_block blk554 := symRun { noAlias := true } seg554 (pcOf 554) 2
sym_block blk555 := symRun { noAlias := true } seg555 (pcOf 555) 5
sym_block blk559 := symRun { noAlias := true } seg559 (pcOf 559) 3
sym_block blk561 := symRun { noAlias := true } seg561 (pcOf 561) 2
sym_block blk562 := symRun { noAlias := true } seg562 (pcOf 562) 4
sym_block blk565 := symRun { noAlias := true } seg565 (pcOf 565) 3
sym_block blk567 := symRun { noAlias := true } seg567 (pcOf 567) 2
sym_block blk568 := symRun { noAlias := true } seg568 (pcOf 568) 2
sym_block blk570 := symRun { noAlias := true } seg570 (pcOf 570) 9
sym_block blk578 := symRun { noAlias := true } seg578 (pcOf 578) 6
sym_block blk583 := symRun { noAlias := true } seg583 (pcOf 583) 5
sym_block blk587 := symRun { noAlias := true } seg587 (pcOf 587) 5
sym_block blk591 := symRun { noAlias := true } seg591 (pcOf 591) 5
sym_block blk595 := symRun { noAlias := true } seg595 (pcOf 595) 8
sym_block blk602 := symRun { noAlias := true } seg602 (pcOf 602) 2
sym_block blk603 := symRun { noAlias := true } seg603 (pcOf 603) 4
sym_block blk606 := symRun { noAlias := true } seg606 (pcOf 606) 3
sym_block blk608 := symRun { noAlias := true } seg608 (pcOf 608) 13
sym_block blk620 := symRun { noAlias := true } seg620 (pcOf 620) 3
sym_block blk622 := symRun { noAlias := true } seg622 (pcOf 622) 8
sym_block blk629 := symRun { noAlias := true } seg629 (pcOf 629) 5
sym_block blk633 := symRun { noAlias := true } seg633 (pcOf 633) 3
sym_block blk635 := symRun { noAlias := true } seg635 (pcOf 635) 3
sym_block blk637 := symRun { noAlias := true } seg637 (pcOf 637) 2
sym_block blk638 := symRun { noAlias := true } seg638 (pcOf 638) 2
sym_block blk639 := symRun { noAlias := true } seg639 (pcOf 639) 35
sym_block blk673 := symRun { noAlias := true } seg673 (pcOf 673) 11
sym_block blk683 := symRun { noAlias := true } seg683 (pcOf 683) 6
sym_block blk696 := symRun { noAlias := true } seg696 (pcOf 696) 6
sym_block blk707 := symRun { noAlias := true } seg707 (pcOf 707) 6
sym_block blk720 := symRun { noAlias := true } seg720 (pcOf 720) 6
sym_block blk731 := symRun { noAlias := true } seg731 (pcOf 731) 6
sym_block blk744 := symRun { noAlias := true } seg744 (pcOf 744) 6
sym_block blk755 := symRun { noAlias := true } seg755 (pcOf 755) 6
sym_block blk768 := symRun { noAlias := true } seg768 (pcOf 768) 6
sym_block blk779 := symRun { noAlias := true } seg779 (pcOf 779) 6
sym_block blk792 := symRun { noAlias := true } seg792 (pcOf 792) 6
sym_block blk803 := symRun { noAlias := true } seg803 (pcOf 803) 2
sym_block blk804 := symRun { noAlias := true } seg804 (pcOf 804) 29
sym_block blk832 := symRun { noAlias := true } seg832 (pcOf 832) 29

sym_block blk2915 := symRun { noAlias := true } seg2915 (pcOf 2915) 4
sym_block blk2918 := symRun { noAlias := true } seg2918 (pcOf 2918) 4
sym_block blk2921 := symRun { noAlias := true } seg2921 (pcOf 2921) 2
sym_block blk2922 := symRun { noAlias := true } seg2922 (pcOf 2922) 4
sym_block blk2925 := symRun { noAlias := true } seg2925 (pcOf 2925) 2
sym_block blk2926 := symRun { noAlias := true } seg2926 (pcOf 2926) 2


theorem carryRun386Low (s : MachineState) (hpc : s.pc=pcOf 386)
    (h4:s.getReg .x8 ≠ 4#64) (hobl : blk386low.res.obligs s) :
    Steps image s 29 32 (blk386low.res.toState s) := by
  have ho := (Oblig.all_iff s _).mp hobl
  have h3:=symRunAux_sound {noAlias:=true} image s segCarryReturn386 (pcOf 392) 100
    blkCarryLow386.res.st _ blk386low codeAt_carryReturn386 ho
  have h2:=symRunAux_sound {noAlias:=true} image s segCarryLow386 (pcOf 2930) 100
    blkCarryTest386.res.st _ blkCarryLow386 codeAt_carryLow386 (fun o h=>ho o (h3.2.1 h))
  have h1:=symRunAux_sound {noAlias:=true} image s segCarryTest386 (pcOf 2927) 100
    blkCarryHead386.res.st _ blkCarryTest386 codeAt_carryTest386 (fun o h=>ho o (h3.2.1 (h2.2.1 h)))
  have h0:=symRun_sound blkCarryHead386 codeAt_386 s hpc
    ((Oblig.all_iff s _).mpr (fun o h=>ho o (h3.2.1 (h2.2.1 (h1.2.1 h)))))
  have hs1:=h1.1
  change Steps image (blkCarryHead386.res.toState s) _ _ _ at hs1
  have hp:blkCarryTest386.res.pc.eval s=pcOf 2930 := by
    simp [blkCarryTest386.res,rv_simp,h4]
  have he:blkCarryTest386.res.toState s=blkCarryTest386.res.st.toState s (pcOf 2930) := by
    simp only [Result.toState,hp]
  have hs2:=h2.1
  rw [←he] at hs2
  have hs3:=h3.1
  change Steps image (blkCarryLow386.res.toState s) _ _ _ at hs3
  exact h0.trans (hs1.trans (hs2.trans hs3))


theorem carryRun386High (s : MachineState) (hpc : s.pc=pcOf 386)
    (h4:s.getReg .x8 = 4#64) (hobl : blk386high.res.obligs s) :
    Steps image s 26 29 (blk386high.res.toState s) := by
  have ho := (Oblig.all_iff s _).mp hobl
  have h3:=symRunAux_sound {noAlias:=true} image s segCarryReturn386 (pcOf 392) 100
    blkCarryHigh386.res.st _ blk386high codeAt_carryReturn386 ho
  have h2:=symRunAux_sound {noAlias:=true} image s segCarryHigh386 (pcOf 2933) 100
    blkCarryTest386.res.st _ blkCarryHigh386 codeAt_carryHigh386 (fun o h=>ho o (h3.2.1 h))
  have h1:=symRunAux_sound {noAlias:=true} image s segCarryTest386 (pcOf 2927) 100
    blkCarryHead386.res.st _ blkCarryTest386 codeAt_carryTest386 (fun o h=>ho o (h3.2.1 (h2.2.1 h)))
  have h0:=symRun_sound blkCarryHead386 codeAt_386 s hpc
    ((Oblig.all_iff s _).mpr (fun o h=>ho o (h3.2.1 (h2.2.1 (h1.2.1 h)))))
  have hs1:=h1.1
  change Steps image (blkCarryHead386.res.toState s) _ _ _ at hs1
  have hp:blkCarryTest386.res.pc.eval s=pcOf 2933 := by
    simp [blkCarryTest386.res,rv_simp,h4]
  have he:blkCarryTest386.res.toState s=blkCarryTest386.res.st.toState s (pcOf 2933) := by
    simp only [Result.toState,hp]
  have hs2:=h2.1
  rw [←he] at hs2
  have hs3:=h3.1
  change Steps image (blkCarryHigh386.res.toState s) _ _ _ at hs3
  exact h0.trans (hs1.trans (hs2.trans hs3))

end SigGolfCandidate.Expand
