-- Generated by gen/gen_expand_lean.py. Do not edit.
import SigGolfCandidate.Expand.Code
import SigGolfCandidate.Sign.Blocks

namespace SigGolfCandidate.Expand
open SigGolfCandidate.Legacy SigGolfCandidate.Legacy.Riscv RiscvZkvm.Rv64 SigGolfCandidate.Rv

/-! Symbolic blocks of the expand program (the word-copy loop bodies are handled by `Copy.lean`;
316 .. 381 are the sign's blocks `Sign.blkN`). -/

sym_block blk0 := symRun { noAlias := true } seg0 (pcOf 0) 15
sym_block blk14 := symRun { noAlias := true } seg14 (pcOf 14) 5
sym_block blk18 := symRun { noAlias := true } seg18 (pcOf 18) 8
sym_block blk25 := symRun { noAlias := true } seg25 (pcOf 25) 6
sym_block blk30 := symRun { noAlias := true } seg30 (pcOf 30) 11
sym_block blk40 := symRun { noAlias := true } seg40 (pcOf 40) 2
sym_block blk41 := symRun { noAlias := true } seg41 (pcOf 41) 4
sym_block blk44 := symRun { noAlias := true } seg44 (pcOf 44) 3
sym_block blk46 := symRun { noAlias := true } seg46 (pcOf 46) 3
sym_block blk48 := symRun { noAlias := true } seg48 (pcOf 48) 4
sym_block blk51 := symRun { noAlias := true } seg51 (pcOf 51) 5
sym_block blk55 := symRun { noAlias := true } seg55 (pcOf 55) 3
sym_block blk57 := symRun { noAlias := true } seg57 (pcOf 57) 8
sym_block blk64 := symRun { noAlias := true } seg64 (pcOf 64) 4
sym_block blk67 := symRun { noAlias := true } seg67 (pcOf 67) 4
sym_block blk70 := symRun { noAlias := true } seg70 (pcOf 70) 3
sym_block blk72 := symRun { noAlias := true } seg72 (pcOf 72) 10
sym_block blk81 := symRun { noAlias := true } seg81 (pcOf 81) 8
sym_block blk88 := symRun { noAlias := true } seg88 (pcOf 88) 4
sym_block blk91 := symRun { noAlias := true } seg91 (pcOf 91) 5
sym_block blk95 := symRun { noAlias := true } seg95 (pcOf 95) 2
sym_block blk96 := symRun { noAlias := true } seg96 (pcOf 96) 3
sym_block blk98 := symRun { noAlias := true } seg98 (pcOf 98) 12
sym_block blk109 := symRun { noAlias := true } seg109 (pcOf 109) 9
sym_block blk117 := symRun { noAlias := true } seg117 (pcOf 117) 3
sym_block blk119 := symRun { noAlias := true } seg119 (pcOf 119) 8
sym_block blk126 := symRun { noAlias := true } seg126 (pcOf 126) 4
sym_block blk129 := symRun { noAlias := true } seg129 (pcOf 129) 4
sym_block blk132 := symRun { noAlias := true } seg132 (pcOf 132) 3
sym_block blk134 := symRun { noAlias := true } seg134 (pcOf 134) 2
sym_block blk135 := symRun { noAlias := true } seg135 (pcOf 135) 3
sym_block blk137 := symRun { noAlias := true } seg137 (pcOf 137) 3
sym_block blk139 := symRun { noAlias := true } seg139 (pcOf 139) 6
sym_block blk150 := symRun { noAlias := true } seg150 (pcOf 150) 4
sym_block blk153 := symRun { noAlias := true } seg153 (pcOf 153) 8
sym_block blk160 := symRun { noAlias := true } seg160 (pcOf 160) 6
sym_block blk173 := symRun { noAlias := true } seg173 (pcOf 173) 2
sym_block blk284 := symRun { noAlias := true } seg284 (pcOf 284) 4
sym_block blk382 := symRun { noAlias := true } seg382 (pcOf 382) 5
sym_block blk408 := symRun { noAlias := true } seg408 (pcOf 408) 5
sym_block blk412 := symRun { noAlias := true } seg412 (pcOf 412) 2
sym_block blk413 := symRun { noAlias := true } seg413 (pcOf 413) 5
sym_block blk417 := symRun { noAlias := true } seg417 (pcOf 417) 3
sym_block blk419 := symRun { noAlias := true } seg419 (pcOf 419) 6
sym_block blk426 := symRun { noAlias := true } seg426 (pcOf 426) 3
sym_block blk428 := symRun { noAlias := true } seg428 (pcOf 428) 11
sym_block blk438 := symRun { noAlias := true } seg438 (pcOf 438) 5
sym_block blk442 := symRun { noAlias := true } seg442 (pcOf 442) 2
sym_block blk446 := symRun { noAlias := true } seg446 (pcOf 446) 11
sym_block blk456 := symRun { noAlias := true } seg456 (pcOf 456) 6
sym_block blk461 := symRun { noAlias := true } seg461 (pcOf 461) 5
sym_block blk465 := symRun { noAlias := true } seg465 (pcOf 465) 5
sym_block blk469 := symRun { noAlias := true } seg469 (pcOf 469) 4
sym_block blk472 := symRun { noAlias := true } seg472 (pcOf 472) 7
sym_block blk1820 := symRun { noAlias := true } seg1820 (pcOf 1820) 7
sym_block blk477 := symRun { noAlias := true } seg477 (pcOf 477) 2
sym_block blk478 := symRun { noAlias := true } seg478 (pcOf 478) 18
sym_block blk495 := symRun { noAlias := true } seg495 (pcOf 495) 35
sym_block blk529 := symRun { noAlias := true } seg529 (pcOf 529) 5
sym_block blk533 := symRun { noAlias := true } seg533 (pcOf 533) 2
sym_block blk534 := symRun { noAlias := true } seg534 (pcOf 534) 3
sym_block blk536 := symRun { noAlias := true } seg536 (pcOf 536) 3
sym_block blk538 := symRun { noAlias := true } seg538 (pcOf 538) 13
sym_block blk550 := symRun { noAlias := true } seg550 (pcOf 550) 5
sym_block blk554 := symRun { noAlias := true } seg554 (pcOf 554) 2
sym_block blk555 := symRun { noAlias := true } seg555 (pcOf 555) 5
sym_block blk559 := symRun { noAlias := true } seg559 (pcOf 559) 3
sym_block blk561 := symRun { noAlias := true } seg561 (pcOf 561) 2
sym_block blk562 := symRun { noAlias := true } seg562 (pcOf 562) 4
sym_block blk565 := symRun { noAlias := true } seg565 (pcOf 565) 3
sym_block blk567 := symRun { noAlias := true } seg567 (pcOf 567) 2
sym_block blk568 := symRun { noAlias := true } seg568 (pcOf 568) 2
sym_block blk570 := symRun { noAlias := true } seg570 (pcOf 570) 9
sym_block blk578 := symRun { noAlias := true } seg578 (pcOf 578) 6
sym_block blk583 := symRun { noAlias := true } seg583 (pcOf 583) 5
sym_block blk587 := symRun { noAlias := true } seg587 (pcOf 587) 5
sym_block blk591 := symRun { noAlias := true } seg591 (pcOf 591) 5
sym_block blk595 := symRun { noAlias := true } seg595 (pcOf 595) 8
sym_block blk602 := symRun { noAlias := true } seg602 (pcOf 602) 2
sym_block blk603 := symRun { noAlias := true } seg603 (pcOf 603) 4
sym_block blk606 := symRun { noAlias := true } seg606 (pcOf 606) 3
sym_block blk608 := symRun { noAlias := true } seg608 (pcOf 608) 13
sym_block blk620 := symRun { noAlias := true } seg620 (pcOf 620) 3
sym_block blk622 := symRun { noAlias := true } seg622 (pcOf 622) 8
sym_block blk629 := symRun { noAlias := true } seg629 (pcOf 629) 5
sym_block blk633 := symRun { noAlias := true } seg633 (pcOf 633) 3
sym_block blk635 := symRun { noAlias := true } seg635 (pcOf 635) 3
sym_block blk637 := symRun { noAlias := true } seg637 (pcOf 637) 2
sym_block blk638 := symRun { noAlias := true } seg638 (pcOf 638) 2
sym_block blk639 := symRun { noAlias := true } seg639 (pcOf 639) 35
sym_block blk673 := symRun { noAlias := true } seg673 (pcOf 673) 11
sym_block blk683 := symRun { noAlias := true } seg683 (pcOf 683) 6
sym_block blk696 := symRun { noAlias := true } seg696 (pcOf 696) 6
sym_block blk707 := symRun { noAlias := true } seg707 (pcOf 707) 6
sym_block blk720 := symRun { noAlias := true } seg720 (pcOf 720) 6
sym_block blk731 := symRun { noAlias := true } seg731 (pcOf 731) 6
sym_block blk744 := symRun { noAlias := true } seg744 (pcOf 744) 6
sym_block blk755 := symRun { noAlias := true } seg755 (pcOf 755) 6
sym_block blk768 := symRun { noAlias := true } seg768 (pcOf 768) 6
sym_block blk779 := symRun { noAlias := true } seg779 (pcOf 779) 6
sym_block blk792 := symRun { noAlias := true } seg792 (pcOf 792) 6
sym_block blk803 := symRun { noAlias := true } seg803 (pcOf 803) 2
sym_block blk804 := symRun { noAlias := true } seg804 (pcOf 804) 29
sym_block blk832 := symRun { noAlias := true } seg832 (pcOf 832) 29

sym_block blk2915 := symRun { noAlias := true } seg2915 (pcOf 2915) 4
sym_block blk2918 := symRun { noAlias := true } seg2918 (pcOf 2918) 4
sym_block blk2921 := symRun { noAlias := true } seg2921 (pcOf 2921) 2
sym_block blk2922 := symRun { noAlias := true } seg2922 (pcOf 2922) 4
sym_block blk2925 := symRun { noAlias := true } seg2925 (pcOf 2925) 2
sym_block blk2926 := symRun { noAlias := true } seg2926 (pcOf 2926) 2


sym_block encHead331 := symRun {noAlias:=true} seg331 (pcOf 331) 100
sym_block encTest331 := symRunAux {noAlias:=true} segMaskEncTest (pcOf 2934) 100 encHead331.res.st
sym_block encLow331 := symRunAux {noAlias:=true} segMaskEncLow (pcOf 2935) 100 encTest331.res.st
sym_block encHigh331 := symRunAux {noAlias:=true} segMaskEncHigh (pcOf 2936) 100 encTest331.res.st
sym_block encLowRes331 := symRunAux {noAlias:=true} segMaskEncReturn (pcOf 343) 100 encLow331.res.st
sym_block encHighRes331 := symRunAux {noAlias:=true} segMaskEncReturn (pcOf 343) 100 encHigh331.res.st
sym_block blk331 := some { encLowRes331.res with st := { encLowRes331.res.st with
  regs := {
    r1 := if E.beq encHighRes331.res.st.regs.r1 encLowRes331.res.st.regs.r1 then encLowRes331.res.st.regs.r1 else E.ite .eq (.reg .x8) (.c 4) encHighRes331.res.st.regs.r1 encLowRes331.res.st.regs.r1,
    r2 := if E.beq encHighRes331.res.st.regs.r2 encLowRes331.res.st.regs.r2 then encLowRes331.res.st.regs.r2 else E.ite .eq (.reg .x8) (.c 4) encHighRes331.res.st.regs.r2 encLowRes331.res.st.regs.r2,
    r3 := if E.beq encHighRes331.res.st.regs.r3 encLowRes331.res.st.regs.r3 then encLowRes331.res.st.regs.r3 else E.ite .eq (.reg .x8) (.c 4) encHighRes331.res.st.regs.r3 encLowRes331.res.st.regs.r3,
    r4 := if E.beq encHighRes331.res.st.regs.r4 encLowRes331.res.st.regs.r4 then encLowRes331.res.st.regs.r4 else E.ite .eq (.reg .x8) (.c 4) encHighRes331.res.st.regs.r4 encLowRes331.res.st.regs.r4,
    r5 := if E.beq encHighRes331.res.st.regs.r5 encLowRes331.res.st.regs.r5 then encLowRes331.res.st.regs.r5 else E.ite .eq (.reg .x8) (.c 4) encHighRes331.res.st.regs.r5 encLowRes331.res.st.regs.r5,
    r6 := if E.beq encHighRes331.res.st.regs.r6 encLowRes331.res.st.regs.r6 then encLowRes331.res.st.regs.r6 else E.ite .eq (.reg .x8) (.c 4) encHighRes331.res.st.regs.r6 encLowRes331.res.st.regs.r6,
    r7 := if E.beq encHighRes331.res.st.regs.r7 encLowRes331.res.st.regs.r7 then encLowRes331.res.st.regs.r7 else E.ite .eq (.reg .x8) (.c 4) encHighRes331.res.st.regs.r7 encLowRes331.res.st.regs.r7,
    r8 := if E.beq encHighRes331.res.st.regs.r8 encLowRes331.res.st.regs.r8 then encLowRes331.res.st.regs.r8 else E.ite .eq (.reg .x8) (.c 4) encHighRes331.res.st.regs.r8 encLowRes331.res.st.regs.r8,
    r9 := if E.beq encHighRes331.res.st.regs.r9 encLowRes331.res.st.regs.r9 then encLowRes331.res.st.regs.r9 else E.ite .eq (.reg .x8) (.c 4) encHighRes331.res.st.regs.r9 encLowRes331.res.st.regs.r9,
    r10 := if E.beq encHighRes331.res.st.regs.r10 encLowRes331.res.st.regs.r10 then encLowRes331.res.st.regs.r10 else E.ite .eq (.reg .x8) (.c 4) encHighRes331.res.st.regs.r10 encLowRes331.res.st.regs.r10,
    r11 := if E.beq encHighRes331.res.st.regs.r11 encLowRes331.res.st.regs.r11 then encLowRes331.res.st.regs.r11 else E.ite .eq (.reg .x8) (.c 4) encHighRes331.res.st.regs.r11 encLowRes331.res.st.regs.r11,
    r12 := if E.beq encHighRes331.res.st.regs.r12 encLowRes331.res.st.regs.r12 then encLowRes331.res.st.regs.r12 else E.ite .eq (.reg .x8) (.c 4) encHighRes331.res.st.regs.r12 encLowRes331.res.st.regs.r12,
    r13 := if E.beq encHighRes331.res.st.regs.r13 encLowRes331.res.st.regs.r13 then encLowRes331.res.st.regs.r13 else E.ite .eq (.reg .x8) (.c 4) encHighRes331.res.st.regs.r13 encLowRes331.res.st.regs.r13,
    r14 := if E.beq encHighRes331.res.st.regs.r14 encLowRes331.res.st.regs.r14 then encLowRes331.res.st.regs.r14 else E.ite .eq (.reg .x8) (.c 4) encHighRes331.res.st.regs.r14 encLowRes331.res.st.regs.r14,
    r15 := if E.beq encHighRes331.res.st.regs.r15 encLowRes331.res.st.regs.r15 then encLowRes331.res.st.regs.r15 else E.ite .eq (.reg .x8) (.c 4) encHighRes331.res.st.regs.r15 encLowRes331.res.st.regs.r15,
    r16 := if E.beq encHighRes331.res.st.regs.r16 encLowRes331.res.st.regs.r16 then encLowRes331.res.st.regs.r16 else E.ite .eq (.reg .x8) (.c 4) encHighRes331.res.st.regs.r16 encLowRes331.res.st.regs.r16,
    r17 := if E.beq encHighRes331.res.st.regs.r17 encLowRes331.res.st.regs.r17 then encLowRes331.res.st.regs.r17 else E.ite .eq (.reg .x8) (.c 4) encHighRes331.res.st.regs.r17 encLowRes331.res.st.regs.r17,
    r18 := if E.beq encHighRes331.res.st.regs.r18 encLowRes331.res.st.regs.r18 then encLowRes331.res.st.regs.r18 else E.ite .eq (.reg .x8) (.c 4) encHighRes331.res.st.regs.r18 encLowRes331.res.st.regs.r18,
    r19 := if E.beq encHighRes331.res.st.regs.r19 encLowRes331.res.st.regs.r19 then encLowRes331.res.st.regs.r19 else E.ite .eq (.reg .x8) (.c 4) encHighRes331.res.st.regs.r19 encLowRes331.res.st.regs.r19,
    r20 := if E.beq encHighRes331.res.st.regs.r20 encLowRes331.res.st.regs.r20 then encLowRes331.res.st.regs.r20 else E.ite .eq (.reg .x8) (.c 4) encHighRes331.res.st.regs.r20 encLowRes331.res.st.regs.r20,
    r21 := if E.beq encHighRes331.res.st.regs.r21 encLowRes331.res.st.regs.r21 then encLowRes331.res.st.regs.r21 else E.ite .eq (.reg .x8) (.c 4) encHighRes331.res.st.regs.r21 encLowRes331.res.st.regs.r21,
    r22 := if E.beq encHighRes331.res.st.regs.r22 encLowRes331.res.st.regs.r22 then encLowRes331.res.st.regs.r22 else E.ite .eq (.reg .x8) (.c 4) encHighRes331.res.st.regs.r22 encLowRes331.res.st.regs.r22,
    r23 := if E.beq encHighRes331.res.st.regs.r23 encLowRes331.res.st.regs.r23 then encLowRes331.res.st.regs.r23 else E.ite .eq (.reg .x8) (.c 4) encHighRes331.res.st.regs.r23 encLowRes331.res.st.regs.r23,
    r24 := if E.beq encHighRes331.res.st.regs.r24 encLowRes331.res.st.regs.r24 then encLowRes331.res.st.regs.r24 else E.ite .eq (.reg .x8) (.c 4) encHighRes331.res.st.regs.r24 encLowRes331.res.st.regs.r24,
    r25 := if E.beq encHighRes331.res.st.regs.r25 encLowRes331.res.st.regs.r25 then encLowRes331.res.st.regs.r25 else E.ite .eq (.reg .x8) (.c 4) encHighRes331.res.st.regs.r25 encLowRes331.res.st.regs.r25,
    r26 := if E.beq encHighRes331.res.st.regs.r26 encLowRes331.res.st.regs.r26 then encLowRes331.res.st.regs.r26 else E.ite .eq (.reg .x8) (.c 4) encHighRes331.res.st.regs.r26 encLowRes331.res.st.regs.r26,
    r27 := if E.beq encHighRes331.res.st.regs.r27 encLowRes331.res.st.regs.r27 then encLowRes331.res.st.regs.r27 else E.ite .eq (.reg .x8) (.c 4) encHighRes331.res.st.regs.r27 encLowRes331.res.st.regs.r27,
    r28 := if E.beq encHighRes331.res.st.regs.r28 encLowRes331.res.st.regs.r28 then encLowRes331.res.st.regs.r28 else E.ite .eq (.reg .x8) (.c 4) encHighRes331.res.st.regs.r28 encLowRes331.res.st.regs.r28,
    r29 := if E.beq encHighRes331.res.st.regs.r29 encLowRes331.res.st.regs.r29 then encLowRes331.res.st.regs.r29 else E.ite .eq (.reg .x8) (.c 4) encHighRes331.res.st.regs.r29 encLowRes331.res.st.regs.r29,
    r30 := if E.beq encHighRes331.res.st.regs.r30 encLowRes331.res.st.regs.r30 then encLowRes331.res.st.regs.r30 else E.ite .eq (.reg .x8) (.c 4) encHighRes331.res.st.regs.r30 encLowRes331.res.st.regs.r30,
    r31 := if E.beq encHighRes331.res.st.regs.r31 encLowRes331.res.st.regs.r31 then encLowRes331.res.st.regs.r31 else E.ite .eq (.reg .x8) (.c 4) encHighRes331.res.st.regs.r31 encLowRes331.res.st.regs.r31 },
  mem := List.zipWith (fun p q => (p.1, if E.beq p.2 q.2 then p.2 else E.ite .eq (.reg .x8) (.c 4) q.2 p.2)) encLowRes331.res.st.mem encHighRes331.res.st.mem } }

theorem encRun331 (s : MachineState) (hpc:s.pc=pcOf 331) :
    ∃ k c, Steps image s k c (blk331.res.toState s) ∧ c≤18 := by
  by_cases isRoot : s.getReg .x8=4#64
  · have h0 := symRun_sound encHead331 codeAt_331 s hpc (by simp only [encHead331.res,rv_simp])
    have h1 := (symRunAux_sound {noAlias:=true} image s segMaskEncTest (pcOf 2934) 100
      encHead331.res.st _ encTest331 codeAt_maskEncTest (by
        apply (Oblig.all_iff s _).mp; simp only [encTest331.res,rv_simp])).1
    have hp1 : encHead331.res.pc.eval s = pcOf 2934 := by simp [encHead331.res,rv_simp,isRoot]
    have he1 : encHead331.res.st.toState s (pcOf 2934) = encHead331.res.toState s := by unfold Result.toState; rw [hp1]
    rw [he1] at h1
    have h2 := (symRunAux_sound {noAlias:=true} image s segMaskEncHigh (pcOf 2936) 100
      encTest331.res.st _ encHigh331 codeAt_maskEncHigh (by
        apply (Oblig.all_iff s _).mp; simp only [encHigh331.res,rv_simp])).1
    have hp2 : encTest331.res.pc.eval s = pcOf 2936 := by simp [encTest331.res,rv_simp,isRoot]
    have he2 : encTest331.res.st.toState s (pcOf 2936) = encTest331.res.toState s := by unfold Result.toState; rw [hp2]
    rw [he2] at h2
    have h3 := (symRunAux_sound {noAlias:=true} image s segMaskEncReturn (pcOf 343) 100
      encHigh331.res.st _ encHighRes331 codeAt_maskEncReturn (by
        apply (Oblig.all_iff s _).mp; simp only [encHighRes331.res,rv_simp])).1
    have hp3 : encHigh331.res.pc.eval s = pcOf 343 := by simp [encHigh331.res,rv_simp,isRoot]
    have he3 : encHigh331.res.st.toState s (pcOf 343) = encHigh331.res.toState s := by unfold Result.toState; rw [hp3]
    rw [he3] at h3
    have he : blk331.res.toState s = encHighRes331.res.toState s := by
      simp only [blk331.res,encHighRes331.res,Result.toState,SymState.toState,
        memEval,Addr.eval,E.eval,CmpOp.eval,BinOp.eval,RegFile.get,beq_iff_eq,isRoot,↓reduceIte]
      all_goals (congr 1 <;> funext r <;> cases r <;> simp [E.eval,CmpOp.eval,BinOp.eval,isRoot])
    rw [he]
    exact ⟨_,_,h0.trans (h1.trans (h2.trans (h3))),by decide⟩
  · have h0 := symRun_sound encHead331 codeAt_331 s hpc (by simp only [encHead331.res,rv_simp])
    have h1 := (symRunAux_sound {noAlias:=true} image s segMaskEncTest (pcOf 2934) 100
      encHead331.res.st _ encTest331 codeAt_maskEncTest (by
        apply (Oblig.all_iff s _).mp; simp only [encTest331.res,rv_simp])).1
    have hp1 : encHead331.res.pc.eval s = pcOf 2934 := by simp [encHead331.res,rv_simp,isRoot]
    have he1 : encHead331.res.st.toState s (pcOf 2934) = encHead331.res.toState s := by unfold Result.toState; rw [hp1]
    rw [he1] at h1
    have h2 := (symRunAux_sound {noAlias:=true} image s segMaskEncLow (pcOf 2935) 100
      encTest331.res.st _ encLow331 codeAt_maskEncLow (by
        apply (Oblig.all_iff s _).mp; simp only [encLow331.res,rv_simp])).1
    have hp2 : encTest331.res.pc.eval s = pcOf 2935 := by simp [encTest331.res,rv_simp,isRoot]
    have he2 : encTest331.res.st.toState s (pcOf 2935) = encTest331.res.toState s := by unfold Result.toState; rw [hp2]
    rw [he2] at h2
    have h3 := (symRunAux_sound {noAlias:=true} image s segMaskEncReturn (pcOf 343) 100
      encLow331.res.st _ encLowRes331 codeAt_maskEncReturn (by
        apply (Oblig.all_iff s _).mp; simp only [encLowRes331.res,rv_simp])).1
    have hp3 : encLow331.res.pc.eval s = pcOf 343 := by simp [encLow331.res,rv_simp,isRoot]
    have he3 : encLow331.res.st.toState s (pcOf 343) = encLow331.res.toState s := by unfold Result.toState; rw [hp3]
    rw [he3] at h3
    have he : blk331.res.toState s = encLowRes331.res.toState s := by
      simp only [blk331.res,encLowRes331.res,Result.toState,SymState.toState,
        memEval,Addr.eval,E.eval,CmpOp.eval,BinOp.eval,RegFile.get,beq_iff_eq,isRoot,↓reduceIte]
      all_goals (congr 1 <;> funext r <;> cases r <;> simp [E.eval,CmpOp.eval,BinOp.eval,isRoot])
    rw [he]
    exact ⟨_,_,h0.trans (h1.trans (h2.trans (h3))),by decide⟩

theorem encRun331_sign (s : MachineState) (hpc:s.pc=pcOf 331) :
    ∃ k c, Steps image s k c (Sign.blk331.res.toState s) ∧ c≤18 := by
  have h : blk331.res = Sign.blk331.res := by kernel_rfl
  simpa only [h] using encRun331 s hpc

sym_block b386low0 := symRun {noAlias:=true} seg386 (pcOf 386) 100
sym_block b386low1 := symRunAux {noAlias:=true} segMaskLeafTest4 (pcOf 2937) 100 b386low0.res.st
sym_block b386low2 := symRunAux {noAlias:=true} segMaskLeafTest3 (pcOf 2940) 100 b386low1.res.st
sym_block b386low3 := symRunAux {noAlias:=true} segMaskLeafLow (pcOf 2943) 100 b386low2.res.st
sym_block b386low4 := symRunAux {noAlias:=true} segMaskLeafReturn (pcOf 393) 100 b386low3.res.st
sym_block b386low5 := symRunAux {noAlias:=true} segMaskNodeTest (pcOf 2946) 100 b386low4.res.st
sym_block b386low6 := symRunAux {noAlias:=true} segMaskNodeLow (pcOf 2951) 100 b386low5.res.st
sym_block blk386low := symRunAux {noAlias:=true} segMaskNodeReturn (pcOf 396) 100 b386low6.res.st

theorem carryRun386Low (s : MachineState) (hpc:s.pc=pcOf 386) (isRoot:s.getReg .x8 ≠ 4#64) (isMid:s.getReg .x8 ≠ 3#64)
    (hobl: blk386low.res.obligs s) :
    Steps image s 36 39 (blk386low.res.toState s) := by
  have ho := (Oblig.all_iff s _).mp hobl
  have h7 := symRunAux_sound {noAlias:=true} image s segMaskNodeReturn (pcOf 396) 100
    b386low6.res.st _ blk386low codeAt_maskNodeReturn ho
  have h6 := symRunAux_sound {noAlias:=true} image s segMaskNodeLow (pcOf 2951) 100
    b386low5.res.st _ b386low6 codeAt_maskNodeLow (fun o h => ho o (h7.2.1 h))
  have h5 := symRunAux_sound {noAlias:=true} image s segMaskNodeTest (pcOf 2946) 100
    b386low4.res.st _ b386low5 codeAt_maskNodeTest (fun o h => ho o (h7.2.1 (h6.2.1 h)))
  have h4 := symRunAux_sound {noAlias:=true} image s segMaskLeafReturn (pcOf 393) 100
    b386low3.res.st _ b386low4 codeAt_maskLeafReturn (fun o h => ho o (h7.2.1 (h6.2.1 (h5.2.1 h))))
  have h3 := symRunAux_sound {noAlias:=true} image s segMaskLeafLow (pcOf 2943) 100
    b386low2.res.st _ b386low3 codeAt_maskLeafLow (fun o h => ho o (h7.2.1 (h6.2.1 (h5.2.1 (h4.2.1 h)))))
  have h2 := symRunAux_sound {noAlias:=true} image s segMaskLeafTest3 (pcOf 2940) 100
    b386low1.res.st _ b386low2 codeAt_maskLeafTest3 (fun o h => ho o (h7.2.1 (h6.2.1 (h5.2.1 (h4.2.1 (h3.2.1 h))))))
  have h1 := symRunAux_sound {noAlias:=true} image s segMaskLeafTest4 (pcOf 2937) 100
    b386low0.res.st _ b386low1 codeAt_maskLeafTest4 (fun o h => ho o (h7.2.1 (h6.2.1 (h5.2.1 (h4.2.1 (h3.2.1 (h2.2.1 h)))))))
  have h0 := symRun_sound b386low0 codeAt_386 s hpc ((Oblig.all_iff s _).mpr (fun o h => ho o (h7.2.1 (h6.2.1 (h5.2.1 (h4.2.1 (h3.2.1 (h2.2.1 (h1.2.1 h)))))))))
  have hp1 : b386low0.res.pc.eval s = pcOf 2937 := by simp [b386low0.res,rv_simp,isRoot,isMid]
  have he1 : b386low0.res.st.toState s (pcOf 2937) = b386low0.res.toState s := by unfold Result.toState; rw [hp1]
  have hs1:=h1.1
  rw [he1] at hs1
  have hp2 : b386low1.res.pc.eval s = pcOf 2940 := by simp [b386low1.res,rv_simp,isRoot,isMid]
  have he2 : b386low1.res.st.toState s (pcOf 2940) = b386low1.res.toState s := by unfold Result.toState; rw [hp2]
  have hs2:=h2.1
  rw [he2] at hs2
  have hp3 : b386low2.res.pc.eval s = pcOf 2943 := by simp [b386low2.res,rv_simp,isRoot,isMid]
  have he3 : b386low2.res.st.toState s (pcOf 2943) = b386low2.res.toState s := by unfold Result.toState; rw [hp3]
  have hs3:=h3.1
  rw [he3] at hs3
  have hp4 : b386low3.res.pc.eval s = pcOf 393 := by simp [b386low3.res,rv_simp,isRoot,isMid]
  have he4 : b386low3.res.st.toState s (pcOf 393) = b386low3.res.toState s := by unfold Result.toState; rw [hp4]
  have hs4:=h4.1
  rw [he4] at hs4
  have hp5 : b386low4.res.pc.eval s = pcOf 2946 := by simp [b386low4.res,rv_simp,isRoot,isMid]
  have he5 : b386low4.res.st.toState s (pcOf 2946) = b386low4.res.toState s := by unfold Result.toState; rw [hp5]
  have hs5:=h5.1
  rw [he5] at hs5
  have hp6 : b386low5.res.pc.eval s = pcOf 2951 := by simp [b386low5.res,rv_simp,isRoot,isMid]
  have he6 : b386low5.res.st.toState s (pcOf 2951) = b386low5.res.toState s := by unfold Result.toState; rw [hp6]
  have hs6:=h6.1
  rw [he6] at hs6
  have hp7 : b386low6.res.pc.eval s = pcOf 396 := by simp [b386low6.res,rv_simp,isRoot,isMid]
  have he7 : b386low6.res.st.toState s (pcOf 396) = b386low6.res.toState s := by unfold Result.toState; rw [hp7]
  have hs7:=h7.1
  rw [he7] at hs7
  exact h0.trans (hs1.trans (hs2.trans (hs3.trans (hs4.trans (hs5.trans (hs6.trans (hs7)))))))

sym_block b386mid0 := symRun {noAlias:=true} seg386 (pcOf 386) 100
sym_block b386mid1 := symRunAux {noAlias:=true} segMaskLeafTest4 (pcOf 2937) 100 b386mid0.res.st
sym_block b386mid2 := symRunAux {noAlias:=true} segMaskLeafTest3 (pcOf 2940) 100 b386mid1.res.st
sym_block b386mid3 := symRunAux {noAlias:=true} segMaskLeafHigh (pcOf 2945) 100 b386mid2.res.st
sym_block b386mid4 := symRunAux {noAlias:=true} segMaskLeafReturn (pcOf 393) 100 b386mid3.res.st
sym_block b386mid5 := symRunAux {noAlias:=true} segMaskNodeTest (pcOf 2946) 100 b386mid4.res.st
sym_block b386mid6 := symRunAux {noAlias:=true} segMaskNodeLow (pcOf 2951) 100 b386mid5.res.st
sym_block blk386mid := symRunAux {noAlias:=true} segMaskNodeReturn (pcOf 396) 100 b386mid6.res.st

theorem carryRun386Mid (s : MachineState) (hpc:s.pc=pcOf 386) (isRoot:s.getReg .x8 ≠ 4#64) (isMid:s.getReg .x8 = 3#64)
    (hobl: blk386mid.res.obligs s) :
    Steps image s 34 37 (blk386mid.res.toState s) := by
  have ho := (Oblig.all_iff s _).mp hobl
  have h7 := symRunAux_sound {noAlias:=true} image s segMaskNodeReturn (pcOf 396) 100
    b386mid6.res.st _ blk386mid codeAt_maskNodeReturn ho
  have h6 := symRunAux_sound {noAlias:=true} image s segMaskNodeLow (pcOf 2951) 100
    b386mid5.res.st _ b386mid6 codeAt_maskNodeLow (fun o h => ho o (h7.2.1 h))
  have h5 := symRunAux_sound {noAlias:=true} image s segMaskNodeTest (pcOf 2946) 100
    b386mid4.res.st _ b386mid5 codeAt_maskNodeTest (fun o h => ho o (h7.2.1 (h6.2.1 h)))
  have h4 := symRunAux_sound {noAlias:=true} image s segMaskLeafReturn (pcOf 393) 100
    b386mid3.res.st _ b386mid4 codeAt_maskLeafReturn (fun o h => ho o (h7.2.1 (h6.2.1 (h5.2.1 h))))
  have h3 := symRunAux_sound {noAlias:=true} image s segMaskLeafHigh (pcOf 2945) 100
    b386mid2.res.st _ b386mid3 codeAt_maskLeafHigh (fun o h => ho o (h7.2.1 (h6.2.1 (h5.2.1 (h4.2.1 h)))))
  have h2 := symRunAux_sound {noAlias:=true} image s segMaskLeafTest3 (pcOf 2940) 100
    b386mid1.res.st _ b386mid2 codeAt_maskLeafTest3 (fun o h => ho o (h7.2.1 (h6.2.1 (h5.2.1 (h4.2.1 (h3.2.1 h))))))
  have h1 := symRunAux_sound {noAlias:=true} image s segMaskLeafTest4 (pcOf 2937) 100
    b386mid0.res.st _ b386mid1 codeAt_maskLeafTest4 (fun o h => ho o (h7.2.1 (h6.2.1 (h5.2.1 (h4.2.1 (h3.2.1 (h2.2.1 h)))))))
  have h0 := symRun_sound b386mid0 codeAt_386 s hpc ((Oblig.all_iff s _).mpr (fun o h => ho o (h7.2.1 (h6.2.1 (h5.2.1 (h4.2.1 (h3.2.1 (h2.2.1 (h1.2.1 h)))))))))
  have hp1 : b386mid0.res.pc.eval s = pcOf 2937 := by simp [b386mid0.res,rv_simp,isRoot,isMid]
  have he1 : b386mid0.res.st.toState s (pcOf 2937) = b386mid0.res.toState s := by unfold Result.toState; rw [hp1]
  have hs1:=h1.1
  rw [he1] at hs1
  have hp2 : b386mid1.res.pc.eval s = pcOf 2940 := by simp [b386mid1.res,rv_simp,isRoot,isMid]
  have he2 : b386mid1.res.st.toState s (pcOf 2940) = b386mid1.res.toState s := by unfold Result.toState; rw [hp2]
  have hs2:=h2.1
  rw [he2] at hs2
  have hp3 : b386mid2.res.pc.eval s = pcOf 2945 := by simp [b386mid2.res,rv_simp,isRoot,isMid]
  have he3 : b386mid2.res.st.toState s (pcOf 2945) = b386mid2.res.toState s := by unfold Result.toState; rw [hp3]
  have hs3:=h3.1
  rw [he3] at hs3
  have hp4 : b386mid3.res.pc.eval s = pcOf 393 := by simp [b386mid3.res,rv_simp,isRoot,isMid]
  have he4 : b386mid3.res.st.toState s (pcOf 393) = b386mid3.res.toState s := by unfold Result.toState; rw [hp4]
  have hs4:=h4.1
  rw [he4] at hs4
  have hp5 : b386mid4.res.pc.eval s = pcOf 2946 := by simp [b386mid4.res,rv_simp,isRoot,isMid]
  have he5 : b386mid4.res.st.toState s (pcOf 2946) = b386mid4.res.toState s := by unfold Result.toState; rw [hp5]
  have hs5:=h5.1
  rw [he5] at hs5
  have hp6 : b386mid5.res.pc.eval s = pcOf 2951 := by simp [b386mid5.res,rv_simp,isRoot,isMid]
  have he6 : b386mid5.res.st.toState s (pcOf 2951) = b386mid5.res.toState s := by unfold Result.toState; rw [hp6]
  have hs6:=h6.1
  rw [he6] at hs6
  have hp7 : b386mid6.res.pc.eval s = pcOf 396 := by simp [b386mid6.res,rv_simp,isRoot,isMid]
  have he7 : b386mid6.res.st.toState s (pcOf 396) = b386mid6.res.toState s := by unfold Result.toState; rw [hp7]
  have hs7:=h7.1
  rw [he7] at hs7
  exact h0.trans (hs1.trans (hs2.trans (hs3.trans (hs4.trans (hs5.trans (hs6.trans (hs7)))))))

sym_block b386high0 := symRun {noAlias:=true} seg386 (pcOf 386) 100
sym_block b386high1 := symRunAux {noAlias:=true} segMaskLeafTest4 (pcOf 2937) 100 b386high0.res.st
sym_block b386high2 := symRunAux {noAlias:=true} segMaskLeafHigh (pcOf 2945) 100 b386high1.res.st
sym_block b386high3 := symRunAux {noAlias:=true} segMaskLeafReturn (pcOf 393) 100 b386high2.res.st
sym_block b386high4 := symRunAux {noAlias:=true} segMaskNodeTest (pcOf 2946) 100 b386high3.res.st
sym_block b386high5 := symRunAux {noAlias:=true} segMaskNodeHigh (pcOf 2952) 100 b386high4.res.st
sym_block blk386high := symRunAux {noAlias:=true} segMaskNodeReturn (pcOf 396) 100 b386high5.res.st

theorem carryRun386High (s : MachineState) (hpc:s.pc=pcOf 386) (isRoot:s.getReg .x8 = 4#64)
    (hobl: blk386high.res.obligs s) :
    Steps image s 30 33 (blk386high.res.toState s) := by
  have ho := (Oblig.all_iff s _).mp hobl
  have h6 := symRunAux_sound {noAlias:=true} image s segMaskNodeReturn (pcOf 396) 100
    b386high5.res.st _ blk386high codeAt_maskNodeReturn ho
  have h5 := symRunAux_sound {noAlias:=true} image s segMaskNodeHigh (pcOf 2952) 100
    b386high4.res.st _ b386high5 codeAt_maskNodeHigh (fun o h => ho o (h6.2.1 h))
  have h4 := symRunAux_sound {noAlias:=true} image s segMaskNodeTest (pcOf 2946) 100
    b386high3.res.st _ b386high4 codeAt_maskNodeTest (fun o h => ho o (h6.2.1 (h5.2.1 h)))
  have h3 := symRunAux_sound {noAlias:=true} image s segMaskLeafReturn (pcOf 393) 100
    b386high2.res.st _ b386high3 codeAt_maskLeafReturn (fun o h => ho o (h6.2.1 (h5.2.1 (h4.2.1 h))))
  have h2 := symRunAux_sound {noAlias:=true} image s segMaskLeafHigh (pcOf 2945) 100
    b386high1.res.st _ b386high2 codeAt_maskLeafHigh (fun o h => ho o (h6.2.1 (h5.2.1 (h4.2.1 (h3.2.1 h)))))
  have h1 := symRunAux_sound {noAlias:=true} image s segMaskLeafTest4 (pcOf 2937) 100
    b386high0.res.st _ b386high1 codeAt_maskLeafTest4 (fun o h => ho o (h6.2.1 (h5.2.1 (h4.2.1 (h3.2.1 (h2.2.1 h))))))
  have h0 := symRun_sound b386high0 codeAt_386 s hpc ((Oblig.all_iff s _).mpr (fun o h => ho o (h6.2.1 (h5.2.1 (h4.2.1 (h3.2.1 (h2.2.1 (h1.2.1 h))))))))
  have hp1 : b386high0.res.pc.eval s = pcOf 2937 := by simp [b386high0.res,rv_simp,isRoot]
  have he1 : b386high0.res.st.toState s (pcOf 2937) = b386high0.res.toState s := by unfold Result.toState; rw [hp1]
  have hs1:=h1.1
  rw [he1] at hs1
  have hp2 : b386high1.res.pc.eval s = pcOf 2945 := by simp [b386high1.res,rv_simp,isRoot]
  have he2 : b386high1.res.st.toState s (pcOf 2945) = b386high1.res.toState s := by unfold Result.toState; rw [hp2]
  have hs2:=h2.1
  rw [he2] at hs2
  have hp3 : b386high2.res.pc.eval s = pcOf 393 := by simp [b386high2.res,rv_simp,isRoot]
  have he3 : b386high2.res.st.toState s (pcOf 393) = b386high2.res.toState s := by unfold Result.toState; rw [hp3]
  have hs3:=h3.1
  rw [he3] at hs3
  have hp4 : b386high3.res.pc.eval s = pcOf 2946 := by simp [b386high3.res,rv_simp,isRoot]
  have he4 : b386high3.res.st.toState s (pcOf 2946) = b386high3.res.toState s := by unfold Result.toState; rw [hp4]
  have hs4:=h4.1
  rw [he4] at hs4
  have hp5 : b386high4.res.pc.eval s = pcOf 2952 := by simp [b386high4.res,rv_simp,isRoot]
  have he5 : b386high4.res.st.toState s (pcOf 2952) = b386high4.res.toState s := by unfold Result.toState; rw [hp5]
  have hs5:=h5.1
  rw [he5] at hs5
  have hp6 : b386high5.res.pc.eval s = pcOf 396 := by simp [b386high5.res,rv_simp,isRoot]
  have he6 : b386high5.res.st.toState s (pcOf 396) = b386high5.res.toState s := by unfold Result.toState; rw [hp6]
  have hs6:=h6.1
  rw [he6] at hs6
  exact h0.trans (hs1.trans (hs2.trans (hs3.trans (hs4.trans (hs5.trans (hs6))))))

sym_block blkAuth860 := symRun { noAlias := true } segAuth860 (pcOf 860) 6
sym_block blkAuth873 := symRun { noAlias := true } segAuth873 (pcOf 873) 6
sym_block blkAuth884 := symRun { noAlias := true } segAuth884 (pcOf 884) 6
sym_block blkAuth897 := symRun { noAlias := true } segAuth897 (pcOf 897) 6
sym_block blkAuth910 := symRun { noAlias := true } segAuth910 (pcOf 910) 6
sym_block blkAuth923 := symRun { noAlias := true } segAuth923 (pcOf 923) 6
sym_block blkAuth936 := symRun { noAlias := true } segAuth936 (pcOf 936) 6
sym_block blkAuth949 := symRun { noAlias := true } segAuth949 (pcOf 949) 6
sym_block blkAuth962 := symRun { noAlias := true } segAuth962 (pcOf 962) 6
sym_block blkAuth975 := symRun { noAlias := true } segAuth975 (pcOf 975) 6
sym_block blkAuth988 := symRun { noAlias := true } segAuth988 (pcOf 988) 2

end SigGolfCandidate.Expand
