-- Generated by the isolated counterpack RV64 design script.
import SigGolfCandidate.Expand.CounterUnpackLayout

namespace SigGolfCandidate.Expand

set_option maxRecDepth 16384

/-- Packed-tail expander segment at instruction 171, 5 words. -/
def seg171Packed : List (BitVec 32) := [
  0x00004337#32, 0xb6030313#32, 0x000013b7#32, 0x17838393#32, 0x0d400b13#32
]
/-- Packed-tail expander segment at instruction 176, 6 words. -/
def seg176Packed : List (BitVec 32) := [
  0x00036183#32, 0x0033a023#32, 0x00430313#32, 0x00438393#32, 0xfffb0b13#32, 0xfe0b16e3#32
]
/-- Packed-tail expander segment at instruction 182, 5 words. -/
def seg182Packed : List (BitVec 32) := [
  0x00004337#32, 0xeb030313#32, 0x000013b7#32, 0x4c838393#32, 0x0c000b13#32
]
/-- Packed-tail expander segment at instruction 187, 6 words. -/
def seg187Packed : List (BitVec 32) := [
  0x00036183#32, 0x0033a023#32, 0x00430313#32, 0x00438393#32, 0xfffb0b13#32, 0xfe0b16e3#32
]
/-- Packed-tail expander segment at instruction 193, 5 words. -/
def seg193Packed : List (BitVec 32) := [
  0x00004337#32, 0x1b030313#32, 0x000013b7#32, 0x7c838393#32, 0x0c000b13#32
]
/-- Packed-tail expander segment at instruction 198, 6 words. -/
def seg198Packed : List (BitVec 32) := [
  0x00036183#32, 0x0033a023#32, 0x00430313#32, 0x00438393#32, 0xfffb0b13#32, 0xfe0b16e3#32
]
/-- Packed-tail expander segment at instruction 204, 5 words. -/
def seg204Packed : List (BitVec 32) := [
  0x00004337#32, 0x4b030313#32, 0x000023b7#32, 0xac838393#32, 0x0c000b13#32
]
/-- Packed-tail expander segment at instruction 209, 6 words. -/
def seg209Packed : List (BitVec 32) := [
  0x00036183#32, 0x0033a023#32, 0x00430313#32, 0x00438393#32, 0xfffb0b13#32, 0xfe0b16e3#32
]
/-- Packed-tail expander segment at instruction 215, 5 words. -/
def seg215Packed : List (BitVec 32) := [
  0x00004337#32, 0x7b030313#32, 0x000023b7#32, 0xdc838393#32, 0x0bc00b13#32
]
/-- Packed-tail expander segment at instruction 220, 6 words. -/
def seg220Packed : List (BitVec 32) := [
  0x00036183#32, 0x0033a023#32, 0x00430313#32, 0x00438393#32, 0xfffb0b13#32, 0xfe0b16e3#32
]
/-- Packed-tail expander segment at instruction 226, 55 words. -/
def seg226Packed : List (BitVec 32) := [
  0x00033583#32, 0x00836603#32, 0x00e65693#32, 0x0003d737#32, 0x2c370713#32, 0x00e6b733#32, 0x00174713#32, 0x0c071663#32,
  0x00008837#32, 0xfff80813#32, 0x01100893#32, 0x0105f733#32, 0x0316f7b3#32, 0x0316d6b3#32, 0x00f79793#32, 0x00f70733#32,
  0x00e3a023#32, 0x00f5d713#32, 0x01077733#32, 0x0316f7b3#32, 0x0316d6b3#32, 0x00f79793#32, 0x00f70733#32, 0x00e3a223#32,
  0x01e5d713#32, 0x01077733#32, 0x0316f7b3#32, 0x0316d6b3#32, 0x00f79793#32, 0x00f70733#32, 0x00e3a423#32, 0x02d5d713#32,
  0x01077733#32, 0x0316f7b3#32, 0x0316d6b3#32, 0x00f79793#32, 0x00f70733#32, 0x00e3a623#32, 0x03c5d713#32, 0x00185813#32,
  0x010677b3#32, 0x00479793#32, 0x00f70733#32, 0x01269693#32, 0x00d70733#32, 0x00e3a823#32, 0x0240006f#32, 0x00000013#32,
  0x00000013#32, 0x00000013#32, 0x00000013#32, 0x00000013#32, 0x00000013#32, 0x00000013#32, 0x00000013#32
]

end SigGolfCandidate.Expand
