-- Generated by t1tools/gen_lean_w1a.py (m3x+ptab8+fcount).
namespace SigGolfCandidate.Verify

/-- Start of the PORS setup (`pors_setup`), of the leaf codes `leaf_s`, the reject stub. -/
def setupPc : Nat := 34
def leafTab : List Nat := [135, 149, 164, 179, 194, 209, 224, 239, 254, 269, 284, 299, 314, 329, 344]
def rejectPc : Nat := 363
def porsRejPc : Nat := 363
def badSegPc : Nat := 366
/-- The two dispatch tables (256 slots of 8 instructions, the entry code inlined): normal
leaves, last leaf. -/
def ptabN : Nat := 367
def ptabL : Nat := 2415
/-- The tails `entry0_V` [V] (V = M, P, F). -/
def entry0Tab : List Nat := [4463, 4774, 5067]
/-- Ladder positions `lad_V_t_p` [V][t][p]. -/
def ladTab : List (List (List Nat)) := [[[4625, 4635, 4645, 4655, 4665, 4675, 4685, 4695, 4705, 4715, 4725, 4735, 4745, 4755], [4476, 4486, 4496, 4506, 4516, 4526, 4536, 4546, 4556, 4566, 4576, 4586, 4596, 4606]], [[4924, 4934, 4944, 4954, 4964, 4974, 4984, 4994, 5004, 5014, 5024, 5034, 5044, 5054], [4781, 4791, 4801, 4811, 4821, 4831, 4841, 4851, 4861, 4871, 4881, 4891, 4901, 4911]], [[5361, 5371, 5381, 5391, 5401, 5411, 5421, 5431, 5441, 5451, 5461, 5471, 5481, 5491], [5145, 5155, 5165, 5175, 5185, 5195, 5205, 5215, 5225, 5235, 5245, 5255, 5265, 5275]]]
/-- Branch continuations `lbr_V_t_p` [V][t][p] (p = 0: unused). -/
def lbrTab : List (List (List Nat)) := [[[0, 4633, 4643, 4653, 4663, 4673, 4683, 4693, 4703, 4713, 4723, 4733, 4743, 4753], [0, 4484, 4494, 4504, 4514, 4524, 4534, 4544, 4554, 4564, 4574, 4584, 4594, 4604]], [[0, 4932, 4942, 4952, 4962, 4972, 4982, 4992, 5002, 5012, 5022, 5032, 5042, 5052], [0, 4789, 4799, 4809, 4819, 4829, 4839, 4849, 4859, 4869, 4879, 4889, 4899, 4909]], [[0, 5369, 5379, 5389, 5399, 5409, 5419, 5429, 5439, 5449, 5459, 5469, 5479, 5489], [0, 5153, 5163, 5173, 5183, 5193, 5203, 5213, 5223, 5233, 5243, 5253, 5263, 5273]]]

end SigGolfCandidate.Verify
