-- Generated by t1tools/gen_lean_w1a.py (m3x+ptab8+fcount).
namespace SigGolfCandidate.Verify

/-- Start of the PORS setup (`pors_setup`), of the leaf codes `leaf_s`, the reject stub. -/
def setupPc : Nat := 25
def leafTab : List Nat := [126, 140, 155, 170, 185, 200, 215, 230, 245, 260, 275, 290, 305, 320, 335]
def rejectPc : Nat := 364
def porsRejPc : Nat := 364
def badSegPc : Nat := 367
/-- The two dispatch tables (256 slots of 8 instructions, the entry code inlined): normal
leaves, last leaf. -/
def ptabN : Nat := 368
def ptabL : Nat := 2416
/-- The tails `entry0_V` [V] (V = M, P, F). -/
def entry0Tab : List Nat := [4464, 4775, 5068]
/-- Ladder positions `lad_V_t_p` [V][t][p]. -/
def ladTab : List (List (List Nat)) := [[[4626, 4636, 4646, 4656, 4666, 4676, 4686, 4696, 4706, 4716, 4726, 4736, 4746, 4756], [4477, 4487, 4497, 4507, 4517, 4527, 4537, 4547, 4557, 4567, 4577, 4587, 4597, 4607]], [[4925, 4935, 4945, 4955, 4965, 4975, 4985, 4995, 5005, 5015, 5025, 5035, 5045, 5055], [4782, 4792, 4802, 4812, 4822, 4832, 4842, 4852, 4862, 4872, 4882, 4892, 4902, 4912]], [[5363, 5373, 5383, 5393, 5403, 5413, 5423, 5433, 5443, 5453, 5463, 5473, 5483, 5493], [5147, 5157, 5167, 5177, 5187, 5197, 5207, 5217, 5227, 5237, 5247, 5257, 5267, 5277]]]
/-- Branch continuations `lbr_V_t_p` [V][t][p] (p = 0: unused). -/
def lbrTab : List (List (List Nat)) := [[[0, 4634, 4644, 4654, 4664, 4674, 4684, 4694, 4704, 4714, 4724, 4734, 4744, 4754], [0, 4485, 4495, 4505, 4515, 4525, 4535, 4545, 4555, 4565, 4575, 4585, 4595, 4605]], [[0, 4933, 4943, 4953, 4963, 4973, 4983, 4993, 5003, 5013, 5023, 5033, 5043, 5053], [0, 4790, 4800, 4810, 4820, 4830, 4840, 4850, 4860, 4870, 4880, 4890, 4900, 4910]], [[0, 5371, 5381, 5391, 5401, 5411, 5421, 5431, 5441, 5451, 5461, 5471, 5481, 5491], [0, 5155, 5165, 5175, 5185, 5195, 5205, 5215, 5225, 5235, 5245, 5255, 5265, 5275]]]

end SigGolfCandidate.Verify
