-- Generated by t0tools/gen_lean.py (gen/verify, m3x+ptab8+fcount).
namespace SigGolfCandidate.Verify

/-- Start of the PORS setup (`pors_setup`), of the leaf codes `leaf_s`, the reject stub. -/
def setupPc : Nat := 29
def leafTab : List Nat := [135, 149, 164, 179, 194, 209, 224, 239, 254, 269, 284, 299, 314, 329, 344]
def rejectPc : Nat := 363
def porsRejPc : Nat := 363
def badSegPc : Nat := 366
/-- The two dispatch tables (255 slots of 8 instructions, the entry code inlined): normal
leaves, last leaf. -/
def ptabN : Nat := 367
def ptabL : Nat := 2415
/-- The tails `entry0_V` [V] (V = M, P, F). -/
def entry0Tab : List Nat := [4463, 4774, 5067]
/-- Ladder positions `lad_V_t_p` [V][t][p]. -/
def ladTab : List (List (List Nat)) := [[[4625, 4635, 4645, 4655, 4665, 4675, 4685, 4695, 4705, 4715, 4725, 4735, 4745, 4755], [4476, 4486, 4496, 4506, 4516, 4526, 4536, 4546, 4556, 4566, 4576, 4586, 4596, 4606]], [[4924, 4934, 4944, 4954, 4964, 4974, 4984, 4994, 5004, 5014, 5024, 5034, 5044, 5054], [4781, 4791, 4801, 4811, 4821, 4831, 4841, 4851, 4861, 4871, 4881, 4891, 4901, 4911]], [[5345, 5355, 5365, 5375, 5385, 5395, 5405, 5415, 5425, 5435, 5445, 5455, 5465, 5475], [5138, 5148, 5158, 5168, 5178, 5188, 5198, 5208, 5218, 5228, 5238, 5248, 5258, 5268]]]
/-- Branch continuations `lbr_V_t_p` [V][t][p] (p = 0: unused). -/
def lbrTab : List (List (List Nat)) := [[[0, 4633, 4643, 4653, 4663, 4673, 4683, 4693, 4703, 4713, 4723, 4733, 4743, 4753], [0, 4484, 4494, 4504, 4514, 4524, 4534, 4544, 4554, 4564, 4574, 4584, 4594, 4604]], [[0, 4932, 4942, 4952, 4962, 4972, 4982, 4992, 5002, 5012, 5022, 5032, 5042, 5052], [0, 4789, 4799, 4809, 4819, 4829, 4839, 4849, 4859, 4869, 4879, 4889, 4899, 4909]], [[0, 5353, 5363, 5373, 5383, 5393, 5403, 5413, 5423, 5433, 5443, 5453, 5463, 5473], [0, 5146, 5156, 5166, 5176, 5186, 5196, 5206, 5216, 5226, 5236, 5246, 5256, 5266]]]

end SigGolfCandidate.Verify
