-- Generated by SigGolfCandidate/Sign/gen_code.py. Do not edit.
import SigGolfCandidate.Sign.Code

namespace SigGolfCandidate.Sign
open SigGolfCandidate.Legacy SigGolfCandidate.Legacy.Riscv RiscvZkvm.Rv64 SigGolfCandidate.Rv

/-! Symbolic blocks of the sign program (before the pack). -/

sym_block blk0 := symRun { noAlias := true } seg0 (pcOf 0) 56
sym_block blk55 := symRun { noAlias := true } seg55 (pcOf 55) 3
sym_block blk57 := symRun { noAlias := true } seg57 (pcOf 57) 3
sym_block blk59 := symRun { noAlias := true } seg59 (pcOf 59) 3
sym_block blk61 := symRun { noAlias := true } seg61 (pcOf 61) 3
sym_block blk63 := symRun { noAlias := true } seg63 (pcOf 63) 3
sym_block blk65 := symRun { noAlias := true } seg65 (pcOf 65) 6
sym_block blk70 := symRun { noAlias := true } seg70 (pcOf 70) 2
sym_block blk72 := symRun { noAlias := true } seg72 (pcOf 72) 7
sym_block blk78 := symRun { noAlias := true } seg78 (pcOf 78) 5
sym_block blk82 := symRun { noAlias := true } seg82 (pcOf 82) 8
sym_block blk89 := symRun { noAlias := true } seg89 (pcOf 89) 6
sym_block blk94 := symRun { noAlias := true } seg94 (pcOf 94) 11
sym_block blk104 := symRun { noAlias := true } seg104 (pcOf 104) 2
sym_block blk105 := symRun { noAlias := true } seg105 (pcOf 105) 4
sym_block blk108 := symRun { noAlias := true } seg108 (pcOf 108) 3
sym_block blk110 := symRun { noAlias := true } seg110 (pcOf 110) 3
sym_block blk112 := symRun { noAlias := true } seg112 (pcOf 112) 4
sym_block blk115 := symRun { noAlias := true } seg115 (pcOf 115) 5
sym_block blk119 := symRun { noAlias := true } seg119 (pcOf 119) 3
sym_block blk121 := symRun { noAlias := true } seg121 (pcOf 121) 8
sym_block blk128 := symRun { noAlias := true } seg128 (pcOf 128) 4
sym_block blk131 := symRun { noAlias := true } seg131 (pcOf 131) 4
sym_block blk134 := symRun { noAlias := true } seg134 (pcOf 134) 3
sym_block blk136 := symRun { noAlias := true } seg136 (pcOf 136) 2
sym_block blk137 := symRun { noAlias := true } seg137 (pcOf 137) 2
sym_block blk138 := symRun { noAlias := true } seg138 (pcOf 138) 2
sym_block blk139 := symRun { noAlias := true } seg139 (pcOf 139) 4
sym_block blk142 := symRun { noAlias := true } seg142 (pcOf 142) 4
sym_block blk145 := symRun { noAlias := true } seg145 (pcOf 145) 35
sym_block blk179 := symRun { noAlias := true } seg179 (pcOf 179) 3
sym_block blk181 := symRun { noAlias := true } seg181 (pcOf 181) 7
sym_block blk187 := symRun { noAlias := true } seg187 (pcOf 187) 8
sym_block blk194 := symRun { noAlias := true } seg194 (pcOf 194) 9
sym_block blk202 := symRun { noAlias := true } seg202 (pcOf 202) 7
sym_block blk208 := symRun { noAlias := true } seg208 (pcOf 208) 3
sym_block blk210 := symRun { noAlias := true } seg210 (pcOf 210) 2
sym_block blk211 := symRun { noAlias := true } seg211 (pcOf 211) 5
sym_block blk215 := symRun { noAlias := true } seg215 (pcOf 215) 2
sym_block blk216 := symRun { noAlias := true } seg216 (pcOf 216) 17
sym_block blk232 := symRun { noAlias := true } seg232 (pcOf 232) 3
sym_block blk234 := symRun { noAlias := true } seg234 (pcOf 234) 5
sym_block blk238 := symRun { noAlias := true } seg238 (pcOf 238) 12
sym_block blk249 := symRun { noAlias := true } seg249 (pcOf 249) 8
sym_block blk256 := symRun { noAlias := true } seg256 (pcOf 256) 4
sym_block blk259 := symRun { noAlias := true } seg259 (pcOf 259) 5
sym_block blk263 := symRun { noAlias := true } seg263 (pcOf 263) 2
sym_block blk264 := symRun { noAlias := true } seg264 (pcOf 264) 3
sym_block blk266 := symRun { noAlias := true } seg266 (pcOf 266) 6
sym_block blk271 := symRun { noAlias := true } seg271 (pcOf 271) 16
sym_block blk286 := symRun { noAlias := true } seg286 (pcOf 286) 3
sym_block blk288 := symRun { noAlias := true } seg288 (pcOf 288) 3
sym_block blk290 := symRun { noAlias := true } seg290 (pcOf 290) 4
sym_block blk293 := symRun { noAlias := true } seg293 (pcOf 293) 4
sym_block blk296 := symRun { noAlias := true } seg296 (pcOf 296) 21
sym_block blk316 := symRun { noAlias := true } seg316 (pcOf 316) 3
sym_block blk318 := symRun { noAlias := true } seg318 (pcOf 318) 4
sym_block blk321 := symRun { noAlias := true } seg321 (pcOf 321) 2
sym_block blk322 := symRun { noAlias := true } seg322 (pcOf 322) 8
sym_block blk329 := symRun { noAlias := true } seg329 (pcOf 329) 3
sym_block blk331 := symRun { noAlias := true } seg331 (pcOf 331) 16
sym_block blk346 := symRun { noAlias := true } seg346 (pcOf 346) 6
sym_block blk351 := symRun { noAlias := true } seg351 (pcOf 351) 5
sym_block blk353 := symRun { noAlias := true } seg353 (pcOf 353) 3
sym_block blk1800 := symRun { noAlias := true } seg1800 (pcOf 1800) 16
sym_block blk355 := symRun { noAlias := true } seg355 (pcOf 355) 22
sym_block blk376 := symRun { noAlias := true } seg376 (pcOf 376) 2
sym_block blk377 := symRun { noAlias := true } seg377 (pcOf 377) 3
sym_block blk379 := symRun { noAlias := true } seg379 (pcOf 379) 4
sym_block blk382 := symRun { noAlias := true } seg382 (pcOf 382) 128
sym_block carryHead509 := symRun {noAlias:=true} seg509 (pcOf 509) 100
sym_block carryTest509 := symRunAux {noAlias:=true} segCarryTest509 (pcOf 3034) 100 carryHead509.res.st
sym_block carryLow509 := symRunAux {noAlias:=true} segCarryLow509 (pcOf 3037) 100 carryTest509.res.st
sym_block carryHigh509 := symRunAux {noAlias:=true} segCarryHigh509 (pcOf 3040) 100 carryTest509.res.st
sym_block carryLowRes509 := symRunAux {noAlias:=true} segCarryReturn509 (pcOf 516) 100 carryLow509.res.st
sym_block carryHighRes509 := symRunAux {noAlias:=true} segCarryReturn509 (pcOf 516) 100 carryHigh509.res.st
sym_block blk509 := some { carryLowRes509.res with st := {carryLowRes509.res.st with
  regs := {carryLowRes509.res.st.regs with r29 := E.ite .eq (.reg .x8) (.c 4) carryHighRes509.res.st.regs.r29 carryLowRes509.res.st.regs.r29},
  mem := (List.zipWith (fun p q => (p.1, if E.beq p.2 q.2 then p.2 else E.ite .eq (.reg .x8) (.c 4) q.2 p.2)) carryLowRes509.res.st.mem carryHighRes509.res.st.mem)}}
sym_block blk522 := symRun { noAlias := true } seg522 (pcOf 522) 8
sym_block blk529 := symRun { noAlias := true } seg529 (pcOf 529) 3
sym_block blk531 := symRun { noAlias := true } seg531 (pcOf 531) 7
sym_block blk537 := symRun { noAlias := true } seg537 (pcOf 537) 13
sym_block blk549 := symRun { noAlias := true } seg549 (pcOf 549) 2
sym_block blk550 := symRun { noAlias := true } seg550 (pcOf 550) 7
sym_block blk556 := symRun { noAlias := true } seg556 (pcOf 556) 7
sym_block blk564 := symRun { noAlias := true } seg564 (pcOf 564) 3
sym_block blk566 := symRun { noAlias := true } seg566 (pcOf 566) 2
sym_block blk567 := symRun { noAlias := true } seg567 (pcOf 567) 7
sym_block blk573 := symRun { noAlias := true } seg573 (pcOf 573) 3
sym_block blk575 := symRun { noAlias := true } seg575 (pcOf 575) 10
sym_block blk584 := symRun { noAlias := true } seg584 (pcOf 584) 6
sym_block blk589 := symRun { noAlias := true } seg589 (pcOf 589) 3
sym_block blk591 := symRun { noAlias := true } seg591 (pcOf 591) 2
sym_block blk592 := symRun { noAlias := true } seg592 (pcOf 592) 18
sym_block blk609 := symRun { noAlias := true } seg609 (pcOf 609) 18
sym_block blk626 := symRun { noAlias := true } seg626 (pcOf 626) 3
sym_block blk628 := symRun { noAlias := true } seg628 (pcOf 628) 3
sym_block blk630 := symRun { noAlias := true } seg630 (pcOf 630) 8
sym_block blk637 := symRun { noAlias := true } seg637 (pcOf 637) 10
sym_block blk646 := symRun { noAlias := true } seg646 (pcOf 646) 3
sym_block blk648 := symRun { noAlias := true } seg648 (pcOf 648) 7
sym_block blk654 := symRun { noAlias := true } seg654 (pcOf 654) 12
sym_block blk665 := symRun { noAlias := true } seg665 (pcOf 665) 2
sym_block blk666 := symRun { noAlias := true } seg666 (pcOf 666) 6
sym_block blk673 := symRun { noAlias := true } seg673 (pcOf 673) 4
sym_block blk676 := symRun { noAlias := true } seg676 (pcOf 676) 10
sym_block blk685 := symRun { noAlias := true } seg685 (pcOf 685) 5
sym_block blk689 := symRun { noAlias := true } seg689 (pcOf 689) 13
sym_block blk701 := symRun { noAlias := true } seg701 (pcOf 701) 18

sym_block blk1717 := symRun { noAlias := true } seg1717 (pcOf 1717) 29

sym_block blk2844 := symRun { noAlias := true } seg2844 (pcOf 2844) 44

sym_block blk2893 := symRun { noAlias := true } seg2893 (pcOf 2893) 5
sym_block blk2897 := symRun { noAlias := true } seg2897 (pcOf 2897) 2
sym_block blk2898 := symRun { noAlias := true } seg2898 (pcOf 2898) 3
sym_block blk2900 := symRun { noAlias := true } seg2900 (pcOf 2900) 5
sym_block carryHead2971 := symRun {noAlias:=true} seg2971 (pcOf 2971) 100
sym_block carryThunk2971 := symRunAux {noAlias:=true} segCarryTop2971 (pcOf 3041) 100 carryHead2971.res.st
sym_block blk2971 := symRunAux {noAlias:=true} segCarryReturn2971 (pcOf 2974) 100 carryThunk2971.res.st
sym_block blk2980 := symRun { noAlias := true } seg2980 (pcOf 2980) 2
sym_block blk2981 := symRun { noAlias := true } seg2981 (pcOf 2981) 6
sym_block blk2986 := symRun { noAlias := true } seg2986 (pcOf 2986) 3

sym_block blk375 := symRun { noAlias := true } seg375 (pcOf 375) 2
sym_block blk1816 := symRun { noAlias := true } seg1816 (pcOf 1816) 5
sym_block blk1820 := symRun { noAlias := true } seg1820 (pcOf 1820) 7
sym_block blk635 := symRun { noAlias := true } seg635 (pcOf 635) 3


def treeSetupCost (lay : Nat) : Nat := if lay=4 then 17 else 20

theorem carryRun509 (s : MachineState) (hpc:s.pc=pcOf 509) :
    ∃ k c, Steps image s k c (blk509.res.toState s) ∧ c≤20 := by
  have h0 := symRun_sound carryHead509 codeAt_509 s hpc (by simp only [carryHead509.res,rv_simp])
  have h1 := (symRunAux_sound {noAlias:=true} image s segCarryTest509 (pcOf 3034) 100
    carryHead509.res.st _ carryTest509 codeAt_carryTest509 (by
      apply (Oblig.all_iff s _).mp; simp only [carryTest509.res,rv_simp])).1
  change Steps image (carryHead509.res.toState s) _ _ _ at h1
  by_cases h : s.getReg .x8=4#64
  · have h2 := (symRunAux_sound {noAlias:=true} image s segCarryHigh509 (pcOf 3040) 100
      carryTest509.res.st _ carryHigh509 codeAt_carryHigh509 (by
        apply (Oblig.all_iff s _).mp; simp only [carryHigh509.res,rv_simp])).1
    have h3 := (symRunAux_sound {noAlias:=true} image s segCarryReturn509 (pcOf 516) 100
      carryHigh509.res.st _ carryHighRes509 codeAt_carryReturn509 (by
        apply (Oblig.all_iff s _).mp; simp only [carryHighRes509.res,rv_simp])).1
    have hp : carryTest509.res.pc.eval s=pcOf 3040 := by
      simp [carryTest509.res,rv_simp,h]
    have hs : carryTest509.res.st.toState s (pcOf 3040)=carryTest509.res.toState s := by
      unfold Result.toState; rw [hp]
    rw [hs] at h2
    change Steps image (carryHigh509.res.toState s) _ _ _ at h3
    have he : blk509.res.toState s=carryHighRes509.res.toState s := by
      simp only [blk509.res,carryHighRes509.res,Result.toState,SymState.toState,
        memEval,Addr.eval,E.eval,CmpOp.eval,BinOp.eval,RegFile.get,beq_iff_eq,h,↓reduceIte]
      congr 1
      funext r
      cases r <;> simp [E.eval,CmpOp.eval,BinOp.eval,h]
    rw [he]
    exact ⟨_,_,h0.trans (h1.trans (h2.trans h3)),by decide⟩
  · have h2 := (symRunAux_sound {noAlias:=true} image s segCarryLow509 (pcOf 3037) 100
      carryTest509.res.st _ carryLow509 codeAt_carryLow509 (by
        apply (Oblig.all_iff s _).mp; simp only [carryLow509.res,rv_simp])).1
    have h3 := (symRunAux_sound {noAlias:=true} image s segCarryReturn509 (pcOf 516) 100
      carryLow509.res.st _ carryLowRes509 codeAt_carryReturn509 (by
        apply (Oblig.all_iff s _).mp; simp only [carryLowRes509.res,rv_simp])).1
    have hp : carryTest509.res.pc.eval s=pcOf 3037 := by
      simp [carryTest509.res,rv_simp,h]
    have hs : carryTest509.res.st.toState s (pcOf 3037)=carryTest509.res.toState s := by
      unfold Result.toState; rw [hp]
    rw [hs] at h2
    change Steps image (carryLow509.res.toState s) _ _ _ at h3
    have he : blk509.res.toState s=carryLowRes509.res.toState s := by
      simp only [blk509.res,carryLowRes509.res,Result.toState,SymState.toState,
        memEval,Addr.eval,E.eval,CmpOp.eval,BinOp.eval,RegFile.get,beq_iff_eq,h,↓reduceIte]
      congr 1
      funext r
      cases r <;> simp [E.eval,CmpOp.eval,BinOp.eval,h]
    rw [he]
    exact ⟨_,_,h0.trans (h1.trans (h2.trans h3)),by decide⟩

theorem carryRun2971 (s : MachineState) (hpc:s.pc=pcOf 2971) (hobl:blk2971.res.obligs s) :
    Steps image s 12 12 (blk2971.res.toState s) := by
  have ho := (Oblig.all_iff s _).mp hobl
  have h2 := symRunAux_sound {noAlias:=true} image s segCarryReturn2971 (pcOf 2974) 100
    carryThunk2971.res.st _ blk2971 codeAt_carryReturn2971 ho
  have h1 := symRunAux_sound {noAlias:=true} image s segCarryTop2971 (pcOf 3041) 100
    carryHead2971.res.st _ carryThunk2971 codeAt_carryTop2971 (fun o h=>ho o (h2.2.1 h))
  have h0 := symRun_sound carryHead2971 codeAt_2971 s hpc
    ((Oblig.all_iff s _).mpr (fun o h=>ho o (h2.2.1 (h1.2.1 h))))
  have hs1:=h1.1
  have hs2:=h2.1
  change Steps image (carryHead2971.res.toState s) _ _ _ at hs1
  change Steps image (carryThunk2971.res.toState s) _ _ _ at hs2
  exact h0.trans (hs1.trans hs2)

end SigGolfCandidate.Sign
