-- Generated by the isolated counterpack RV64 design script.
import SigGolfCandidate.Sign.CounterPackLayout

namespace SigGolfCandidate.Sign

set_option maxRecDepth 16384

/-- Redirect the old proven pack to the aligned body/tail appendix; PCs 2844..2886 remain unchanged. -/
def seg2841Packed : List (BitVec 32) := [0x0b80006f#32, 0x00000013#32, 0x00000013#32]

/-- Packed-tail signer body setup at instruction 2887, 5 words. -/
def seg2887Packed : List (BitVec 32) := [
  0x00001337#32, 0x90830313#32, 0x000043b7#32, 0xb6038393#32, 0x0d400b13#32
]

/-- Packed-tail signer body loop at instruction 2892, 6 words. -/
def seg2892Packed : List (BitVec 32) := [
  0x00036183#32, 0x0033a023#32, 0x00430313#32, 0x00438393#32, 0xfffb0b13#32, 0xfe0b16e3#32
]

/-- Packed-tail signer body setup at instruction 2898, 5 words. -/
def seg2898Packed : List (BitVec 32) := [
  0x00001337#32, 0xc6030313#32, 0x000043b7#32, 0xeb038393#32, 0x0c000b13#32
]

/-- Packed-tail signer body loop at instruction 2903, 6 words. -/
def seg2903Packed : List (BitVec 32) := [
  0x00036183#32, 0x0033a023#32, 0x00430313#32, 0x00438393#32, 0xfffb0b13#32, 0xfe0b16e3#32
]

/-- Packed-tail signer body setup at instruction 2909, 5 words. -/
def seg2909Packed : List (BitVec 32) := [
  0x00001337#32, 0xfb830313#32, 0x000043b7#32, 0x1b038393#32, 0x0c000b13#32
]

/-- Packed-tail signer body loop at instruction 2914, 6 words. -/
def seg2914Packed : List (BitVec 32) := [
  0x00036183#32, 0x0033a023#32, 0x00430313#32, 0x00438393#32, 0xfffb0b13#32, 0xfe0b16e3#32
]

/-- Packed-tail signer body setup at instruction 2920, 5 words. -/
def seg2920Packed : List (BitVec 32) := [
  0x00001337#32, 0x31030313#32, 0x000043b7#32, 0x4b038393#32, 0x0c000b13#32
]

/-- Packed-tail signer body loop at instruction 2925, 6 words. -/
def seg2925Packed : List (BitVec 32) := [
  0x00036183#32, 0x0033a023#32, 0x00430313#32, 0x00438393#32, 0xfffb0b13#32, 0xfe0b16e3#32
]

/-- Packed-tail signer body setup at instruction 2931, 5 words. -/
def seg2931Packed : List (BitVec 32) := [
  0x00001337#32, 0x66830313#32, 0x000043b7#32, 0x7b038393#32, 0x0bc00b13#32
]

/-- Packed-tail signer body loop at instruction 2936, 6 words. -/
def seg2936Packed : List (BitVec 32) := [
  0x00036183#32, 0x0033a023#32, 0x00430313#32, 0x00438393#32, 0xfffb0b13#32, 0xfe0b16e3#32
]

/-- Jump to the mixed-radix appendix, preserving the target adjustment at PC 2967. -/
def seg2942Packed : List (BitVec 32) := [
  0x0780006f#32, 0x00000013#32, 0x00000013#32, 0x00000013#32, 0x00000013#32, 0x00000013#32, 0x00000013#32, 0x00000013#32,
  0x00000013#32, 0x00000013#32, 0x00000013#32, 0x00000013#32, 0x00000013#32, 0x00000013#32, 0x00000013#32, 0x00000013#32,
  0x00000013#32, 0x00000013#32, 0x00000013#32, 0x00000013#32, 0x00000013#32, 0x00000013#32, 0x00000013#32, 0x00000013#32,
  0x00000013#32
]

/-- Total counter serializer: bounded tuples use mixed radix, other tuples use the reserved tail. -/
def seg2972Packed : List (BitVec 32) := [
  0x00001e37#32, 0x900e0e13#32, 0x000e6583#32, 0x358e6603#32, 0x6b0e6683#32, 0x00001e37#32, 0x308e0e13#32, 0x000e6703#32,
  0x358e6783#32, 0x00088937#32, 0x0125ba33#32, 0x012639b3#32, 0x013a7a33#32, 0x0126b9b3#32, 0x013a7a33#32, 0x012739b3#32,
  0x013a7a33#32, 0x000c0937#32, 0x0127b9b3#32, 0x013a7a33#32, 0xfffa0a13#32, 0x01100993#32, 0x0127d893#32, 0x033888b3#32,
  0x00f75913#32, 0x012888b3#32, 0x033888b3#32, 0x00f6d913#32, 0x012888b3#32, 0x033888b3#32, 0x00f65913#32, 0x012888b3#32,
  0x033888b3#32, 0x00f5d913#32, 0x012888b3#32, 0x000089b7#32, 0xfff98993#32, 0x0135f833#32, 0x01367933#32, 0x00f91913#32,
  0x01280833#32, 0x0136f933#32, 0x01e91913#32, 0x01280833#32, 0x01377933#32, 0x02d91913#32, 0x01280833#32, 0x000409b7#32,
  0xfff98993#32, 0x0137f933#32, 0x03c91993#32, 0x01380833#32, 0x00495913#32, 0x00e89893#32, 0x012888b3#32, 0x01486833#32,
  0x0148e8b3#32, 0x02089893#32, 0x0208d893#32, 0x00005eb7#32, 0xaa0e8e93#32, 0x010eb023#32, 0x011eb423#32, 0x00100293#32,
  0x00000513#32, 0x00000073#32
]

end SigGolfCandidate.Sign
