-- Generated by gen/gen_sign_lean.py. Do not edit.
import SigGolfCandidate.Sign.PackC0
import SigGolfCandidate.Sign.PackC1
import SigGolfCandidate.Sign.PackC2
import SigGolfCandidate.Sign.PackC3
import SigGolfCandidate.Sign.PackC4

namespace SigGolfCandidate.Sign
open SigGolfCandidate.Legacy SigGolfCandidate.Legacy.Riscv RiscvZkvm.Rv64 SigGolfCandidate.Rv

/-- The whole pack (instructions 718 .. 1713). -/
theorem pack_run : PackStep 718 1714 0 488 996 :=
  ((((packStep_718.comp packStep_934 (by norm_num)).comp packStep_1130 (by norm_num)).comp packStep_1326 (by norm_num)).comp packStep_1522 (by norm_num))

-- The final HALT.
sym_block blk1714 := symRun { noAlias := true } seg1714 (pcOf 1714) 4

end SigGolfCandidate.Sign
