import SigGolfCandidate.Rv.AddressAdapter
import SigGolfCandidate.Expand.Mem
import SigGolfCandidate.Submission

/-!
# `keygen`: segment table and symbolic blocks (generated by `gen_keygen.py`)

`seg_a_b` is instructions `a .. b-1`; `blk_a` its symbolic run (`noAlias`), `codeAt_a` its
placement. The `ecall`s (39, 56, 73, 101, 132, 171, 174) are singleton segments.
-/

namespace SigGolfCandidate.Keygen
open RiscvZkvm.Rv64 SigGolfCandidate.Legacy SigGolfCandidate.Legacy.Riscv SigGolfCandidate.Rv

set_option maxRecDepth 8192
set_option maxHeartbeats 1500000

def seg_0 : List (BitVec 32) := [0x08003083, 0x6c103023, 0x08803083, 0x6c103423, 0x09003083, 0x6c103823, 0x09803083, 0x6c103c23, 0x00000413, 0x00000f13, 0x00b00493, 0x000059b7, 0xb2098993, 0x01041193, 0x0011ee93, 0x6bd02023, 0x1011ee93, 0x0dd02023, 0x3200006f, 0x35d03023, 0x00100193, 0x009198b3, 0x00000a13, 0x0e003023, 0x0e003423]
def seg_25 : List (BitVec 32) := [0x020a1193, 0x01e1e1b3, 0x6a303423, 0x0c303423, 0x34303423, 0x00000a93, 0x00000c13]
def seg_32 : List (BitVec 32) := [0x001af193, 0x00019e63]
def seg_34 : List (BitVec 32) := [0x001ad193, 0x6a302223, 0x6a000513, 0x04000593, 0x14000613]
def seg_39 : List (BitVec 32) := [0x00000073]
def seg_40 : List (BitVec 32) := [0x001af193, 0x00419193, 0x1401b083, 0x1481b103, 0x0e103823, 0x0e203c23, 0x0c000513, 0x0f000613, 0x00000b93]
def seg_49 : List (BitVec 32) := [0x001b8b93, 0x003c5193, 0x00819193, 0x007c7e93, 0x01d1e1b3, 0x0c302223, 0x0c000513]
def seg_56 : List (BitVec 32) := [0x20c0006f]
def seg_57 : List (BitVec 32) := [0x001c0c13, 0x00700193, 0xfc3b9ce3]
def seg_60 : List (BitVec 32) := [0x001c0c13, 0x004a9193, 0x0f003083, 0x0f803103, 0x3611b023, 0x3621b423, 0x001a8a93, 0x02a00193, 0xf63a98e3]
def seg_69 : List (BitVec 32) := [0x34000513, 0x2c000593, 0x004a1193, 0x00398633]
def seg_73 : List (BitVec 32) := [0x00000073]
def seg_74 : List (BitVec 32) := [0x001a0a13, 0xf31a1ce3]
def seg_76 : List (BitVec 32) := [0x00100793]
def seg_77 : List (BitVec 32) := [0x26c0006f, 0x3011e193, 0x1c303023, 0x1de02423, 0x00489193, 0x00398cb3, 0x0018d893, 0x00000813]
def seg_85 : List (BitVec 32) := [0x1f40006f, 0x1c202623, 0x00581193, 0x013181b3, 0x0001b083, 0x1e103023, 0x0081b083, 0x1e103423, 0x0101b083, 0x1e103823, 0x0181b083, 0x1e103c23, 0x1c000513, 0x04000593, 0x00481193, 0x003c8633]
def seg_101 : List (BitVec 32) := [0x00000073]
def seg_102 : List (BitVec 32) := [0x00180813, 0xfb181ce3]
def seg_104 : List (BitVec 32) := [0x000c8993, 0x00178793, 0xf8f4d6e3]
def seg_107 : List (BitVec 32) := [0x0009b083, 0x0089b103, 0x0a103023, 0x0a203423, 0x0009b023, 0x0009b423, 0x0009b823, 0x0009bc23]
def seg_115 : List (BitVec 32) := [0x0000da37, 0xb20a0a13, 0x00100793]
def seg_118 : List (BitVec 32) := [0x00100193, 0x00b00e93, 0x40fe8eb3, 0x01d198b3, 0x00000813]
def seg_123 : List (BitVec 32) := [0x02079193, 0x68118193, 0x68018193, 0x6a303023, 0x02081193, 0x6a303423, 0x6a000513, 0x04000593, 0x14000613]
def seg_132 : List (BitVec 32) := [0x00000073]
def seg_133 : List (BitVec 32) := [0x000a3083, 0x14003103, 0x0020c0b3, 0x001a3023, 0x008a3083, 0x14803103, 0x0020c0b3, 0x001a3423, 0x010a0a13, 0x00180813, 0xfb1818e3]
def seg_144 : List (BitVec 32) := [0x00178793, 0x00b00193, 0xf83798e3]
def seg_147 : List (BitVec 32) := [0x0700006f, 0x00000013]
def seg_171 : List (BitVec 32) := [0x00000073]
def seg_172 : List (BitVec 32) := [0x02c0006f, 0x00000013]
def seg_174 : List (BitVec 32) := [0x00000073]

def seg_149 : List (BitVec 32) := [0x0000deb7, 0xb00e8e93, 0x000011b7, 0xe0118193, 0xfe3eb023, 0x08003083, 0x001eb023, 0x08803083, 0x001eb423, 0x09003083, 0x001eb823, 0x09803083, 0x001ebc23, 0x000a3023, 0x000a3423, 0x000a3823, 0x000a3c23, 0xfe0e8513, 0x000085b7, 0x04058593, 0x0000d637, 0xb0060613]
def seg_175 : List (BitVec 32) := [0x00005eb7, 0xb00e8e93, 0x0000d1b7, 0xb0018193]
def seg_179 : List (BitVec 32) := [0x000eb023, 0x008e8e93, 0xfe3e9ce3]
def seg_182 : List (BitVec 32) := [0xf7dff06f]
def seg_183 : List (BitVec 32) := [0xfe0eb023, 0x00100293, 0x00000513, 0xfd1ff06f]

def segAddrReturn56 : List (BitVec 32) := [0xda1ff06f]

def segPtrReturn85 : List (BitVec 32) := [0x00581193, 0x013181b3, 0x0001b083, 0x1e103023, 0x0081b083, 0x1e103423, 0x0101b083, 0x1e103823, 0x0181b083, 0x1e103c23, 0x1c000513, 0x04000593, 0x00481193, 0x003c8633]
def segPtr210 : List (BitVec 32) := [0x00189193, 0xfff18193, 0x41018133, 0x1c202623, 0xe05ff06f]

def segCarry215 : List (BitVec 32) := [0x00010eb7, 0x301e8e93, 0xce9ff06f]
def segCarryReturn0 : List (BitVec 32) := seg_0.drop 20
def segMask218 : List (BitVec 32) := [0x071c7d37, 0x1c7d0d13, 0x00cd1d13, 0x1c7d0d13, 0x00cd1d13, 0x1c7d0d13, 0x00cd1d13, 0x1c7d0d13, 0x35a03023, 0x00300193, 0x343000a3, 0x00100193, 0x34300123, 0xcb5ff06f]
def segMask232 : List (BitVec 32) := [0x1da03023, 0x00300193, 0x1c3000a3, 0x1c000123, 0xd91ff06f]
def segMaskReturn77 : List (BitVec 32) := seg_77.drop 3

def L : Rv.Layout := [(0, seg_0), (25, seg_25), (32, seg_32), (34, seg_34), (39, seg_39), (40, seg_40), (49, seg_49), (56, seg_56), (57, seg_57), (60, seg_60), (69, seg_69), (73, seg_73), (74, seg_74), (76, seg_76), (77, seg_77), (85, seg_85), (101, seg_101), (102, seg_102), (104, seg_104), (107, seg_107), (115, seg_115), (118, seg_118), (123, seg_123), (132, seg_132), (133, seg_133), (144, seg_144), (147, seg_147), (149, seg_149), (171, seg_171), (172, seg_172), (174, seg_174), (175, seg_175), (179, seg_179), (182, seg_182), (183, seg_183), (187, AddressAdapter.headCode), (206, AddressAdapter.tailCode), (209, segAddrReturn56), (210, segPtr210), (215, segCarry215), (218, segMask218), (232, segMask232)]

theorem layout_ok : layoutOk 0 L = true := by decide +kernel

/-- The keygen image. -/
abbrev image : Image := submission.image .keygen

theorem code_eq : image.code = layoutCode L := by decide +kernel

theorem codeAt_0 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 0)) seg_0 :=
  codeAt_layout code_eq layout_ok (i := 0) (by kernel_rfl) (by decide)
theorem codeAt_25 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 25)) seg_25 :=
  codeAt_layout code_eq layout_ok (i := 1) (by kernel_rfl) (by decide)
theorem codeAt_32 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 32)) seg_32 :=
  codeAt_layout code_eq layout_ok (i := 2) (by kernel_rfl) (by decide)
theorem codeAt_34 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 34)) seg_34 :=
  codeAt_layout code_eq layout_ok (i := 3) (by kernel_rfl) (by decide)
theorem codeAt_39 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 39)) seg_39 :=
  codeAt_layout code_eq layout_ok (i := 4) (by kernel_rfl) (by decide)
theorem codeAt_40 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 40)) seg_40 :=
  codeAt_layout code_eq layout_ok (i := 5) (by kernel_rfl) (by decide)
theorem codeAt_49 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 49)) seg_49 :=
  codeAt_layout code_eq layout_ok (i := 6) (by kernel_rfl) (by decide)
theorem codeAt_56 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 56)) seg_56 :=
  codeAt_layout code_eq layout_ok (i := 7) (by kernel_rfl) (by decide)
theorem codeAt_57 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 57)) seg_57 :=
  codeAt_layout code_eq layout_ok (i := 8) (by kernel_rfl) (by decide)
theorem codeAt_60 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 60)) seg_60 :=
  codeAt_layout code_eq layout_ok (i := 9) (by kernel_rfl) (by decide)
theorem codeAt_69 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 69)) seg_69 :=
  codeAt_layout code_eq layout_ok (i := 10) (by kernel_rfl) (by decide)
theorem codeAt_73 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 73)) seg_73 :=
  codeAt_layout code_eq layout_ok (i := 11) (by kernel_rfl) (by decide)
theorem codeAt_74 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 74)) seg_74 :=
  codeAt_layout code_eq layout_ok (i := 12) (by kernel_rfl) (by decide)
theorem codeAt_76 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 76)) seg_76 :=
  codeAt_layout code_eq layout_ok (i := 13) (by kernel_rfl) (by decide)
theorem codeAt_77 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 77)) seg_77 :=
  codeAt_layout code_eq layout_ok (i := 14) (by kernel_rfl) (by decide)
theorem codeAt_85 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 85)) seg_85 :=
  codeAt_layout code_eq layout_ok (i := 15) (by kernel_rfl) (by decide)
theorem codeAt_101 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 101)) seg_101 :=
  codeAt_layout code_eq layout_ok (i := 16) (by kernel_rfl) (by decide)
theorem codeAt_102 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 102)) seg_102 :=
  codeAt_layout code_eq layout_ok (i := 17) (by kernel_rfl) (by decide)
theorem codeAt_104 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 104)) seg_104 :=
  codeAt_layout code_eq layout_ok (i := 18) (by kernel_rfl) (by decide)
theorem codeAt_107 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 107)) seg_107 :=
  codeAt_layout code_eq layout_ok (i := 19) (by kernel_rfl) (by decide)
theorem codeAt_115 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 115)) seg_115 :=
  codeAt_layout code_eq layout_ok (i := 20) (by kernel_rfl) (by decide)
theorem codeAt_118 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 118)) seg_118 :=
  codeAt_layout code_eq layout_ok (i := 21) (by kernel_rfl) (by decide)
theorem codeAt_123 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 123)) seg_123 :=
  codeAt_layout code_eq layout_ok (i := 22) (by kernel_rfl) (by decide)
theorem codeAt_132 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 132)) seg_132 :=
  codeAt_layout code_eq layout_ok (i := 23) (by kernel_rfl) (by decide)
theorem codeAt_133 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 133)) seg_133 :=
  codeAt_layout code_eq layout_ok (i := 24) (by kernel_rfl) (by decide)
theorem codeAt_144 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 144)) seg_144 :=
  codeAt_layout code_eq layout_ok (i := 25) (by kernel_rfl) (by decide)
theorem codeAt_147 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 147)) seg_147 :=
  codeAt_layout code_eq layout_ok (i := 26) (by kernel_rfl) (by decide)
theorem codeAt_171 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 171)) seg_171 :=
  codeAt_layout code_eq layout_ok (i := 28) (by kernel_rfl) (by decide)
theorem codeAt_172 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 172)) seg_172 :=
  codeAt_layout code_eq layout_ok (i := 29) (by kernel_rfl) (by decide)
theorem codeAt_174 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 174)) seg_174 :=
  codeAt_layout code_eq layout_ok (i := 30) (by kernel_rfl) (by decide)

theorem codeAt_carry215 : CodeAt image (BitVec.ofNat 64 (0x1000+4*215)) segCarry215 := by unfold CodeAt; decide +kernel
theorem codeAt_carryReturn0 : CodeAt image (BitVec.ofNat 64 (0x1000+4*20)) segCarryReturn0 := by unfold CodeAt; decide +kernel
theorem codeAt_mask218 : CodeAt image (BitVec.ofNat 64 (0x1000+4*218)) segMask218 := by unfold CodeAt; decide +kernel
theorem codeAt_mask232 : CodeAt image (BitVec.ofNat 64 (0x1000+4*232)) segMask232 := by unfold CodeAt; decide +kernel
theorem codeAt_maskReturn77 : CodeAt image (BitVec.ofNat 64 (0x1000+4*80)) segMaskReturn77 := by unfold CodeAt; decide +kernel
sym_block blkCarryHead0 := symRun { noAlias := true } seg_0 (BitVec.ofNat 64 0x1000) 100
sym_block blkCarryThunk0 := symRunAux { noAlias := true } segMask218 (BitVec.ofNat 64 (0x1000+4*218)) 100 blkCarryHead0.res.st
sym_block blk_0 := symRunAux { noAlias := true } segCarryReturn0 (BitVec.ofNat 64 (0x1000+4*20)) 100 blkCarryThunk0.res.st
sym_block blk_25 := symRun { noAlias := true } seg_25 (BitVec.ofNat 64 (0x1000 + 4 * 25)) 100
sym_block blk_32 := symRun { noAlias := true } seg_32 (BitVec.ofNat 64 (0x1000 + 4 * 32)) 100
sym_block blk_34 := symRun { noAlias := true } seg_34 (BitVec.ofNat 64 (0x1000 + 4 * 34)) 100
sym_block blk_40 := symRun { noAlias := true } seg_40 (BitVec.ofNat 64 (0x1000 + 4 * 40)) 100
sym_block blk_49 := symRun { noAlias := true } seg_49 (BitVec.ofNat 64 (0x1000 + 4 * 49)) 100
sym_block blk_57 := symRun { noAlias := true } seg_57 (BitVec.ofNat 64 (0x1000 + 4 * 57)) 100
sym_block blk_60 := symRun { noAlias := true } seg_60 (BitVec.ofNat 64 (0x1000 + 4 * 60)) 100
sym_block blk_69 := symRun { noAlias := true } seg_69 (BitVec.ofNat 64 (0x1000 + 4 * 69)) 100
sym_block blk_74 := symRun { noAlias := true } seg_74 (BitVec.ofNat 64 (0x1000 + 4 * 74)) 100
sym_block blk_76 := symRun { noAlias := true } seg_76 (BitVec.ofNat 64 (0x1000 + 4 * 76)) 100
sym_block blkMaskHead77 := symRun { noAlias := true } seg_77 (BitVec.ofNat 64 (0x1000 + 4 * 77)) 100
sym_block blkMaskThunk77 := symRunAux { noAlias := true } segMask232 (BitVec.ofNat 64 (0x1000+4*232)) 100 blkMaskHead77.res.st
sym_block blk_77 := symRunAux { noAlias := true } segMaskReturn77 (BitVec.ofNat 64 (0x1000+4*80)) 100 blkMaskThunk77.res.st
theorem codeAt_ptr210 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 210)) segPtr210 := by unfold CodeAt;decide +kernel
theorem codeAt_ptrReturn85 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 87)) segPtrReturn85 := by unfold CodeAt;decide +kernel
sym_block blkPtrHead85 := symRun { noAlias := true } seg_85 (BitVec.ofNat 64 (0x1000 + 4 * 85)) 100
sym_block blkPtrThunk85 := symRunAux { noAlias := true } segPtr210 (BitVec.ofNat 64 (0x1000 + 4 * 210)) 100 blkPtrHead85.res.st
sym_block blk_85 := symRunAux { noAlias := true } segPtrReturn85 (BitVec.ofNat 64 (0x1000 + 4 * 87)) 100 blkPtrThunk85.res.st

sym_block blk_102 := symRun { noAlias := true } seg_102 (BitVec.ofNat 64 (0x1000 + 4 * 102)) 100
sym_block blk_104 := symRun { noAlias := true } seg_104 (BitVec.ofNat 64 (0x1000 + 4 * 104)) 100
sym_block blk_107 := symRun { noAlias := true } seg_107 (BitVec.ofNat 64 (0x1000 + 4 * 107)) 100
sym_block blk_115 := symRun { noAlias := true } seg_115 (BitVec.ofNat 64 (0x1000 + 4 * 115)) 100
sym_block blk_118 := symRun { noAlias := true } seg_118 (BitVec.ofNat 64 (0x1000 + 4 * 118)) 100
sym_block blk_123 := symRun { noAlias := true } seg_123 (BitVec.ofNat 64 (0x1000 + 4 * 123)) 100
sym_block blk_133 := symRun { noAlias := true } seg_133 (BitVec.ofNat 64 (0x1000 + 4 * 133)) 100
sym_block blk_144 := symRun { noAlias := true } seg_144 (BitVec.ofNat 64 (0x1000 + 4 * 144)) 100
sym_block blk_147 := symRun { noAlias := true } seg_147 (BitVec.ofNat 64 (0x1000 + 4 * 147)) 100
sym_block blk_172 := symRun { noAlias := true } seg_172 (BitVec.ofNat 64 (0x1000 + 4 * 172)) 100

theorem codeAt_149 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 149)) seg_149 :=
  codeAt_layout code_eq layout_ok (i := 27) (by kernel_rfl) (by decide)
sym_block blk_149 := symRun { noAlias := true } seg_149 (BitVec.ofNat 64 (0x1000 + 4 * 149)) 100

theorem codeAt_175 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 175)) seg_175 :=
  codeAt_layout code_eq layout_ok (i := 31) (by kernel_rfl) (by decide)
sym_block blk_175 := symRun { noAlias := true } seg_175 (BitVec.ofNat 64 (0x1000 + 4 * 175)) 100

theorem codeAt_179 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 179)) seg_179 :=
  codeAt_layout code_eq layout_ok (i := 32) (by kernel_rfl) (by decide)
sym_block blk_179 := symRun { noAlias := true } seg_179 (BitVec.ofNat 64 (0x1000 + 4 * 179)) 100

theorem codeAt_182 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 182)) seg_182 :=
  codeAt_layout code_eq layout_ok (i := 33) (by kernel_rfl) (by decide)
sym_block blk_182 := symRun { noAlias := true } seg_182 (BitVec.ofNat 64 (0x1000 + 4 * 182)) 100

theorem codeAt_183 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 183)) seg_183 :=
  codeAt_layout code_eq layout_ok (i := 34) (by kernel_rfl) (by decide)
sym_block blk_183 := symRun { noAlias := true } seg_183 (BitVec.ofNat 64 (0x1000 + 4 * 183)) 100

theorem addrHead56 : CodeAt image ((BitVec.ofNat 64 (0x1000 + 4 * 187))) AddressAdapter.headCode := by unfold CodeAt; decide +kernel
theorem addrTail56 : CodeAt image ((BitVec.ofNat 64 (0x1000 + 4 * 206))) AddressAdapter.tailCode := by unfold CodeAt; decide +kernel
theorem addrJump56 : CodeAt image ((BitVec.ofNat 64 (0x1000 + 4 * 56))) [0x20c0006f#32] := by unfold CodeAt; decide +kernel
theorem addrReturn56 : CodeAt image ((BitVec.ofNat 64 (0x1000 + 4 * 209))) segAddrReturn56 := by unfold CodeAt; decide +kernel
theorem jumpAddress56 (s : MachineState) (hpc : s.pc = (BitVec.ofNat 64 (0x1000 + 4 * 56))) :
    Steps image s 1 1 { s with pc := (BitVec.ofNat 64 (0x1000 + 4 * 187)) } := by
  apply AddressAdapter.jump_step s ((BitVec.ofNat 64 (0x1000 + 4 * 56))) ((BitVec.ofNat 64 (0x1000 + 4 * 187))) (BitVec.ofInt 21 (524)) hpc (by decide +kernel)
  exact (addrJump56.fetch s hpc).trans (by kernel_rfl)
theorem returnAddress56 (s : MachineState) (hpc : s.pc = (BitVec.ofNat 64 (0x1000 + 4 * 209))) :
    Steps image s 1 1 { s with pc := (BitVec.ofNat 64 (0x1000 + 4 * 57)) } := by
  apply AddressAdapter.jump_step s ((BitVec.ofNat 64 (0x1000 + 4 * 209))) ((BitVec.ofNat 64 (0x1000 + 4 * 57))) (BitVec.ofInt 21 (-608)) hpc (by decide +kernel)
  exact (addrReturn56.fetch s hpc).trans (by kernel_rfl)

theorem ptrRun85 (s : MachineState) (hpc : s.pc=(BitVec.ofNat 64 (0x1000 + 4 * 85)))
    (hobl : blk_85.res.obligs s) : Steps image s 20 20 (blk_85.res.toState s) := by
  have ho := (Oblig.all_iff s _).mp hobl
  have hs2 := symRunAux_sound {noAlias:=true} image s segPtrReturn85 (BitVec.ofNat 64 (0x1000 + 4 * 87)) 100
    blkPtrThunk85.res.st _ blk_85 codeAt_ptrReturn85 ho
  have hs1 := symRunAux_sound {noAlias:=true} image s segPtr210 (BitVec.ofNat 64 (0x1000 + 4 * 210)) 100
    blkPtrHead85.res.st _ blkPtrThunk85 codeAt_ptr210 (fun o h=>ho o (hs2.2.1 h))
  have h0 := symRun_sound blkPtrHead85 codeAt_85 s hpc
    ((Oblig.all_iff s _).mpr (fun o h=>ho o (hs2.2.1 (hs1.2.1 h))))
  have h1 := hs1.1
  have h2 := hs2.1
  change Steps image (blkPtrHead85.res.toState s) _ _ _ at h1
  change Steps image (blkPtrThunk85.res.toState s) _ _ _ at h2
  exact h0.trans (h1.trans h2)

theorem carryRun0 (s : MachineState) (hpc : s.pc=(BitVec.ofNat 64 (0x1000 + 4 * 0)))
    (hobl : blk_0.res.obligs s) : Steps image s 38 38 (blk_0.res.toState s) := by
  have ho := (Oblig.all_iff s _).mp hobl
  have hs2 := symRunAux_sound {noAlias:=true} image s segCarryReturn0 (BitVec.ofNat 64 (0x1000 + 4 * 20)) 100
    blkCarryThunk0.res.st _ blk_0 codeAt_carryReturn0 ho
  have hs1 := symRunAux_sound {noAlias:=true} image s segMask218 (BitVec.ofNat 64 (0x1000 + 4 * 218)) 100
    blkCarryHead0.res.st _ blkCarryThunk0 codeAt_mask218 (fun o h=>ho o (hs2.2.1 h))
  have h0 := symRun_sound blkCarryHead0 codeAt_0 s hpc
    ((Oblig.all_iff s _).mpr (fun o h=>ho o (hs2.2.1 (hs1.2.1 h))))
  have h1 := hs1.1
  have h2 := hs2.1
  change Steps image (blkCarryHead0.res.toState s) _ _ _ at h1
  change Steps image (blkCarryThunk0.res.toState s) _ _ _ at h2
  exact h0.trans (h1.trans h2)

theorem maskRun77 (s : MachineState) (hpc : s.pc=(BitVec.ofNat 64 (0x1000 + 4 * 77)))
    (hobl : blk_77.res.obligs s) : Steps image s 11 11 (blk_77.res.toState s) := by
  have ho := (Oblig.all_iff s _).mp hobl
  have hs2 := symRunAux_sound {noAlias:=true} image s segMaskReturn77 (BitVec.ofNat 64 (0x1000 + 4 * 80)) 100
    blkMaskThunk77.res.st _ blk_77 codeAt_maskReturn77 ho
  have hs1 := symRunAux_sound {noAlias:=true} image s segMask232 (BitVec.ofNat 64 (0x1000 + 4 * 232)) 100
    blkMaskHead77.res.st _ blkMaskThunk77 codeAt_mask232 (fun o h=>ho o (hs2.2.1 h))
  have h0 := symRun_sound blkMaskHead77 codeAt_77 s hpc
    ((Oblig.all_iff s _).mpr (fun o h=>ho o (hs2.2.1 (hs1.2.1 h))))
  have h1 := hs1.1
  have h2 := hs2.1
  change Steps image (blkMaskHead77.res.toState s) _ _ _ at h1
  change Steps image (blkMaskThunk77.res.toState s) _ _ _ at h2
  exact h0.trans (h1.trans h2)

end SigGolfCandidate.Keygen
